// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package legaltime.model;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;

import legaltime.model.Manager;
import legaltime.model.exception.DAOException;
import legaltime.model.exception.DataAccessException;
import legaltime.model.exception.ObjectRetrievalException;

/**
 * Handles database calls (save, load, count, etc...) for the expense_invoice_item table.
 * @author sql2java
 */
public class ExpenseInvoiceItemManager 
{

    /* set =QUERY for loadUsingTemplate */
    public static final int SEARCH_EXACT = 0;
    /* set %QUERY% for loadLikeTemplate */
    public static final int SEARCH_LIKE = 1;
    /* set %QUERY for loadLikeTemplate */
    public static final int SEARCH_STARTING_LIKE = 2;
    /* set QUERY% for loadLikeTemplate */
    public static final int SEARCH_ENDING_LIKE = 3;

    /**
     * Identify the last_update field.
     */
    public static final int ID_LAST_UPDATE = 0;

    /**
     * Identify the invoice_id field.
     */
    public static final int ID_INVOICE_ID = 1;

    /**
     * Identify the hours_billed field.
     */
    public static final int ID_HOURS_BILLED = 2;

    /**
     * Identify the expense_description field.
     */
    public static final int ID_EXPENSE_DESCRIPTION = 3;

    /**
     * Identify the expense_date field.
     */
    public static final int ID_EXPENSE_DATE = 4;

    /**
     * Identify the expense_invoice_item_id field.
     */
    public static final int ID_EXPENSE_INVOICE_ITEM_ID = 5;

    /**
     * Contains all the full fields of the expense_invoice_item table.
     */
    private static final String[] FULL_FIELD_NAMES =
    {
        "expense_invoice_item.last_update"
        ,"expense_invoice_item.invoice_id"
        ,"expense_invoice_item.hours_billed"
        ,"expense_invoice_item.expense_description"
        ,"expense_invoice_item.expense_date"
        ,"expense_invoice_item.expense_invoice_item_id"
    };

    /**
     * Contains all the fields of the expense_invoice_item table.
     */
    public static final String[] FIELD_NAMES =
    {
        "last_update"
        ,"invoice_id"
        ,"hours_billed"
        ,"expense_description"
        ,"expense_date"
        ,"expense_invoice_item_id"
    };

    /**
     * Field that contains the comma separated fields of the expense_invoice_item table.
     */
    public static final String ALL_FULL_FIELDS = "expense_invoice_item.last_update"
                            + ",expense_invoice_item.invoice_id"
                            + ",expense_invoice_item.hours_billed"
                            + ",expense_invoice_item.expense_description"
                            + ",expense_invoice_item.expense_date"
                            + ",expense_invoice_item.expense_invoice_item_id";

    /**
     * Field that contains the comma separated fields of the expense_invoice_item table.
     */
    public static final String ALL_FIELDS = "last_update"
                            + ",invoice_id"
                            + ",hours_billed"
                            + ",expense_description"
                            + ",expense_date"
                            + ",expense_invoice_item_id";

    private static ExpenseInvoiceItemManager singleton = new ExpenseInvoiceItemManager();

    /**
     * Get the ExpenseInvoiceItemManager singleton.
     *
     * @return ExpenseInvoiceItemManager
     */
    public static ExpenseInvoiceItemManager getInstance()
    {
        return singleton;
    }


    /**
     * Creates a new ExpenseInvoiceItemBean instance.
     *
     * @return the new ExpenseInvoiceItemBean
     */
    public ExpenseInvoiceItemBean createExpenseInvoiceItemBean()
    {
        return new ExpenseInvoiceItemBean();
    }

    //////////////////////////////////////
    // PRIMARY KEY METHODS
    //////////////////////////////////////

    /**
     * Loads a ExpenseInvoiceItemBean from the expense_invoice_item using its key fields.
     *
     * @param expenseInvoiceItemId Integer - PK# 1
     * @return a unique ExpenseInvoiceItemBean
     * @throws DAOException
     */
    //1
    public ExpenseInvoiceItemBean loadByPrimaryKey(Integer expenseInvoiceItemId) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = this.getConnection();
            StringBuffer sql = new StringBuffer("SELECT " + ALL_FIELDS + " FROM expense_invoice_item WHERE expense_invoice_item_id=?");
            // System.out.println("loadByPrimaryKey: " + sql);
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            if (expenseInvoiceItemId == null) { ps.setNull(1, Types.INTEGER); } else { Manager.setInteger(ps, 1, expenseInvoiceItemId); }
            ExpenseInvoiceItemBean pReturn[] = this.loadByPreparedStatement(ps);
            if (pReturn.length < 1) {
                throw new ObjectRetrievalException();
            } else {
                return pReturn[0];
            }
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Deletes rows according to its keys.
     *
     * @param expenseInvoiceItemId Integer - PK# 1
     * @return the number of deleted rows
     * @throws DAOException
     */
    //2
    public int deleteByPrimaryKey(Integer expenseInvoiceItemId) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = this.getConnection();
            StringBuffer sql = new StringBuffer("DELETE FROM expense_invoice_item WHERE expense_invoice_item_id=?");
            // System.out.println("deleteByPrimaryKey: " + sql);
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            if (expenseInvoiceItemId == null) { ps.setNull(1, Types.INTEGER); } else { Manager.setInteger(ps, 1, expenseInvoiceItemId); }
            return ps.executeUpdate();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }



    //////////////////////////////////////
    // LOAD ALL
    //////////////////////////////////////

    /**
     * Loads all the rows from expense_invoice_item.
     *
     * @return an array of ExpenseInvoiceItemManager bean
     * @throws DAOException
     */
    //5
    public ExpenseInvoiceItemBean[] loadAll() throws DAOException
    {
        return this.loadUsingTemplate(null);
    }


    /**
     * Loads the given number of rows from expense_invoice_item, given the start row.
     *
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return an array of ExpenseInvoiceItemManager bean
     * @throws DAOException
     */
    //6
    public ExpenseInvoiceItemBean[] loadAll(int startRow, int numRows) throws DAOException
    {
        return this.loadUsingTemplate(null, startRow, numRows);
    }

    //////////////////////////////////////
    // SQL 'WHERE' METHOD
    //////////////////////////////////////
    /**
     * Retrieves an array of ExpenseInvoiceItemBean given a sql 'where' clause.
     *
     * @param where the sql 'where' clause
     * @return the resulting ExpenseInvoiceItemBean table
     * @throws DAOException
     */
    //7
    public ExpenseInvoiceItemBean[] loadByWhere(String where) throws DAOException
    {
        return this.loadByWhere(where, null);
    }

    /**
     * Retrieves an array of ExpenseInvoiceItemBean given a sql where clause, and a list of fields.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'WHERE' clause
     * @param fieldList array of field's ID
     * @return the resulting ExpenseInvoiceItemBean table
     * @throws DAOException
     */
    //8
    public ExpenseInvoiceItemBean[] loadByWhere(String where, int[] fieldList) throws DAOException
    {
        return this.loadByWhere(where, fieldList, 1, -1);
    }

    /**
     * Retrieves an array of ExpenseInvoiceItemBean given a sql where clause and a list of fields, and startRow and numRows.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'where' clause
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return the resulting ExpenseInvoiceItemBean table
     * @throws DAOException
     */
    //9
    public ExpenseInvoiceItemBean[] loadByWhere(String where, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        StringBuffer sql = new StringBuffer(128);
        if(fieldList == null) {
            sql.append("SELECT ").append(ALL_FIELDS).append(" FROM expense_invoice_item ").append(where);
        } else
        {
            sql.append("SELECT ");
            for(int i = 0; i < fieldList.length; i++)
            {
                if(i != 0) {
                    sql.append(",");
                }
                sql.append(FULL_FIELD_NAMES[fieldList[i]]);
            }
            sql.append(" FROM expense_invoice_item ");
            sql.append(where);
        }
        Connection c = null;
        Statement st = null;
        ResultSet rs =  null;
        // System.out.println("loadByWhere: " + sql);
        try
        {
            c = this.getConnection();
            st = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = st.executeQuery(sql.toString());
            return this.decodeResultSet(rs, fieldList, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(st, rs);
            this.freeConnection(c);
        }
    }


    /**
     * Deletes all rows from expense_invoice_item table.
     * @return the number of deleted rows.
     * @throws DAOException
     */
    //10
    public int deleteAll() throws DAOException
    {
        return this.deleteByWhere("");
    }


    /**
     * Deletes rows from the expense_invoice_item table using a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     * <br>Attention, if 'WHERE' is omitted it will delete all records.
     *
     * @param where the sql 'where' clause
     * @return the number of deleted rows
     * @throws DAOException
     */
    //11
    public int deleteByWhere(String where) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;

        try
        {
            c = this.getConnection();
            StringBuffer sql = new StringBuffer("DELETE FROM expense_invoice_item " + where);
            // System.out.println("deleteByWhere: " + sql);
            ps = c.prepareStatement(sql.toString());
            return ps.executeUpdate();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    //_____________________________________________________________________
    //
    // SAVE
    //_____________________________________________________________________
    /**
     * Saves the ExpenseInvoiceItemBean bean into the database.
     *
     * @param bean the ExpenseInvoiceItemBean bean to be saved
     * @return the inserted or updated bean
     * @throws DAOException
     */
    //12
    public ExpenseInvoiceItemBean save(ExpenseInvoiceItemBean bean) throws DAOException
    {
        if (bean.isNew()) {
            return this.insert(bean);
        } else {
            return this.update(bean);
        }
    }

    /**
     * Insert the ExpenseInvoiceItemBean bean into the database.
     *
     * @param bean the ExpenseInvoiceItemBean bean to be saved
     * @return the inserted bean
     * @throws DAOException
     */
    //13
    public ExpenseInvoiceItemBean insert(ExpenseInvoiceItemBean bean) throws DAOException
    {
        // mini checks
        if (!bean.isModified()) {
            return bean; // should not we log something ?
        }
        if (!bean.isNew()){
            return this.update(bean);
        }

        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = null;

        try
        {
            c = this.getConnection();
            this.beforeInsert(bean); // listener callback
            int _dirtyCount = 0;
            sql = new StringBuffer("INSERT into expense_invoice_item (");

            if (bean.isLastUpdateModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("last_update");
                _dirtyCount++;
            }

            if (bean.isInvoiceIdModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("invoice_id");
                _dirtyCount++;
            }

            if (bean.isHoursBilledModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("hours_billed");
                _dirtyCount++;
            }

            if (bean.isExpenseDescriptionModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("expense_description");
                _dirtyCount++;
            }

            if (bean.isExpenseDateModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("expense_date");
                _dirtyCount++;
            }

            if (bean.isExpenseInvoiceItemIdModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("expense_invoice_item_id");
                _dirtyCount++;
            }

            sql.append(") values (");
            if(_dirtyCount > 0) {
                sql.append("?");
                for(int i = 1; i < _dirtyCount; i++) {
                    sql.append(",?");
                }
            }
            sql.append(")");


            // System.out.println("insert : " + sql.toString());

            ps = c.prepareStatement(sql.toString(), ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

            this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            ps.executeUpdate();

            if (!bean.isExpenseInvoiceItemIdModified())
            {
                PreparedStatement ps2 = null;
                ResultSet rs = null;
                try {
                    ps2 = c.prepareStatement("SELECT last_insert_id()");
                    rs = ps2.executeQuery();
                    if(rs.next()) {
                        bean.setExpenseInvoiceItemId(Manager.getInteger(rs, 1));
                    } else {
                        this.getManager().log("ATTENTION: Could not retrieve generated key!");
                    }
                } finally {
                    this.getManager().close(ps2, rs);
                }
            }

            bean.isNew(false);
            bean.resetIsModified();
            this.afterInsert(bean); // listener callback
            return bean;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Update the ExpenseInvoiceItemBean bean record in the database according to the changes.
     *
     * @param bean the ExpenseInvoiceItemBean bean to be updated
     * @return the updated bean
     * @throws DAOException
     */
    //14
    public ExpenseInvoiceItemBean update(ExpenseInvoiceItemBean bean) throws DAOException
    {
        // mini checks
        if (!bean.isModified()) {
            return bean; // should not we log something ?
        }
        if (bean.isNew()){
            return this.insert(bean);
        }

        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = null;

        try
        {
            c = this.getConnection();

            this.beforeUpdate(bean); // listener callback
            sql = new StringBuffer("UPDATE expense_invoice_item SET ");
            boolean useComma=false;

            if (bean.isLastUpdateModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("last_update=?");
            }

            if (bean.isInvoiceIdModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("invoice_id=?");
            }

            if (bean.isHoursBilledModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("hours_billed=?");
            }

            if (bean.isExpenseDescriptionModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("expense_description=?");
            }

            if (bean.isExpenseDateModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("expense_date=?");
            }

            if (bean.isExpenseInvoiceItemIdModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("expense_invoice_item_id=?");
            }
            sql.append(" WHERE ");
            sql.append("expense_invoice_item_id=?");
            // System.out.println("update : " + sql.toString());
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);

            int _dirtyCount = this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            if (_dirtyCount == 0) {
                // System.out.println("The bean to look is not initialized... do not update.");
                return bean;
            }

            if (bean.getExpenseInvoiceItemId() == null) { ps.setNull(++_dirtyCount, Types.INTEGER); } else { Manager.setInteger(ps, ++_dirtyCount, bean.getExpenseInvoiceItemId()); }
            ps.executeUpdate();
            bean.resetIsModified();
            this.afterUpdate(bean); // listener callback

            return bean;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Saves an array of ExpenseInvoiceItemBean beans into the database.
     *
     * @param beans the ExpenseInvoiceItemBean bean table to be saved
     * @return the saved ExpenseInvoiceItemBean array.
     * @throws DAOException
     */
    //15
    public ExpenseInvoiceItemBean[] save(ExpenseInvoiceItemBean[] beans) throws DAOException
    {
        for (int iIndex = 0; iIndex < beans.length; iIndex ++)
        {
            this.save(beans[iIndex]);
        }
        return beans;
    }

    /**
     * Insert an array of ExpenseInvoiceItemBean beans into the database.
     *
     * @param beans the ExpenseInvoiceItemBean bean table to be inserted
     * @return the saved ExpenseInvoiceItemBean array.
     * @throws DAOException
     */
    //16
    public ExpenseInvoiceItemBean[] insert(ExpenseInvoiceItemBean[] beans) throws DAOException
    {
        return this.save(beans);
    }

    /**
     * Updates an array of ExpenseInvoiceItemBean beans into the database.
     *
     * @param beans the ExpenseInvoiceItemBean bean table to be inserted
     * @return the saved ExpenseInvoiceItemBean array.
     * @throws DAOException
     */
    //17
    public ExpenseInvoiceItemBean[] update(ExpenseInvoiceItemBean[] beans) throws DAOException
    {
        return this.save(beans);
    }



    //_____________________________________________________________________
    //
    // USING TEMPLATE
    //_____________________________________________________________________
    /**
     * Loads a unique ExpenseInvoiceItemBean bean from a template one giving a c
     *
     * @param bean the ExpenseInvoiceItemBean bean to look for
     * @return the bean matching the template
     * @throws DAOException
     */
    //18
    public ExpenseInvoiceItemBean loadUniqueUsingTemplate(ExpenseInvoiceItemBean bean) throws DAOException
    {
         ExpenseInvoiceItemBean[] beans = this.loadUsingTemplate(bean);
         if (beans.length == 0) {
             return null;
         }
         if (beans.length > 1) {
             throw new ObjectRetrievalException("More than one element !!");
         }
         return beans[0];
     }

    /**
     * Loads an array of ExpenseInvoiceItemBean from a template one.
     *
     * @param bean the ExpenseInvoiceItemBean template to look for
     * @return all the ExpenseInvoiceItemBean matching the template
     * @throws DAOException
     */
    //19
    public ExpenseInvoiceItemBean[] loadUsingTemplate(ExpenseInvoiceItemBean bean) throws DAOException
    {
        return this.loadUsingTemplate(bean, 1, -1);
    }

    /**
     * Loads an array of ExpenseInvoiceItemBean from a template one, given the start row and number of rows.
     *
     * @param bean the ExpenseInvoiceItemBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return all the ExpenseInvoiceItemBean matching the template
     * @throws DAOException
     */
    //20
    public ExpenseInvoiceItemBean[] loadUsingTemplate(ExpenseInvoiceItemBean bean, int startRow, int numRows) throws DAOException
    {
        return this.loadUsingTemplate(bean, startRow, numRows, SEARCH_EXACT);
    }

    /**
     * Loads an array of ExpenseInvoiceItemBean from a template one, given the start row and number of rows.
     *
     * @param bean the ExpenseInvoiceItemBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param searchType exact ?  like ? starting like ?
     * @return all the ExpenseInvoiceItemBean matching the template
     * @throws DAOException
     */
    //20
    public ExpenseInvoiceItemBean[] loadUsingTemplate(ExpenseInvoiceItemBean bean, int startRow, int numRows, int searchType) throws DAOException
    {
        // System.out.println("loadUsingTemplate startRow:" + startRow + ", numRows:" + numRows + ", searchType:" + searchType);
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = new StringBuffer(128);
        sql.append("SELECT ").append(ALL_FIELDS).append(" FROM expense_invoice_item ");
        StringBuffer sqlWhere = new StringBuffer("");

        try
        {
            if (this.fillWhere(sqlWhere, bean, searchType) > 0) {
                sql.append(" WHERE ").append(sqlWhere);
            } else {
               // System.out.println("The bean to look is not initialized... loading all");
            }
            // System.out.println("loadUsingTemplate: " + sql.toString());

            c = this.getConnection();
            int scrollType = ResultSet.TYPE_SCROLL_INSENSITIVE;
            if (startRow != 1) {
                scrollType = ResultSet.TYPE_SCROLL_SENSITIVE;
            }
            ps = c.prepareStatement(sql.toString(),
                                    scrollType,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, searchType);

            ps.executeQuery();
            return this.loadByPreparedStatement(ps, null, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }

    /**
     * Deletes rows using a ExpenseInvoiceItemBean template.
     *
     * @param bean the ExpenseInvoiceItemBean object(s) to be deleted
     * @return the number of deleted objects
     * @throws DAOException
     */
    //21
    public int deleteUsingTemplate(ExpenseInvoiceItemBean bean) throws DAOException
    {
        if (bean.isExpenseInvoiceItemIdInitialized()) {
            return this.deleteByPrimaryKey(bean.getExpenseInvoiceItemId());
        }
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = new StringBuffer("DELETE FROM expense_invoice_item ");
        StringBuffer sqlWhere = new StringBuffer("");

        try
        {
            this.beforeDelete(bean); // listener callback
            if (this.fillWhere(sqlWhere, bean, SEARCH_EXACT) > 0) {
                sql.append(" WHERE ").append(sqlWhere);
            } else {
               // System.out.println("The bean to look is not initialized... deleting all");
            }
            // System.out.println("deleteUsingTemplate: " + sql.toString());

            c = this.getConnection();
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            int _rows = ps.executeUpdate();
            this.afterDelete(bean); // listener callback
            return _rows;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }



    //_____________________________________________________________________
    //
    // COUNT
    //_____________________________________________________________________

    /**
     * Retrieves the number of rows of the table expense_invoice_item.
     *
     * @return the number of rows returned
     * @throws DAOException
     */
    //24
    public int countAll() throws DAOException
    {
        return this.countWhere("");
    }

    /**
     * Retrieves the number of rows of the table expense_invoice_item with a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the restriction clause
     * @return the number of rows returned
     * @throws DAOException
     */
    //25
    public int countWhere(String where) throws DAOException
    {
        String sql = "SELECT COUNT(*) AS MCOUNT FROM expense_invoice_item " + where;
        // System.out.println("countWhere: " + sql);
        Connection c = null;
        Statement st = null;
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            c = this.getConnection();
            st = c.createStatement();
            rs =  st.executeQuery(sql);
            if (rs.next())
            {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1) {
                return iReturn;
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(st, rs);
            this.freeConnection(c);
            sql = null;
        }
        throw new DataAccessException("Error in countWhere where=[" + where + "]");
    }

    /**
     * Retrieves the number of rows of the table expense_invoice_item with a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return the number of rows returned
     * @throws DAOException
     */
    //26
    private int countByPreparedStatement(PreparedStatement ps) throws DAOException
    {
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            rs = ps.executeQuery();
            if (rs.next()) {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1) {
                return iReturn;
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(rs);
        }
       throw new DataAccessException("Error in countByPreparedStatement");
    }

    /**
     * count the number of elements of a specific ExpenseInvoiceItemBean bean
     *
     * @param bean the ExpenseInvoiceItemBean bean to look for ant count
     * @return the number of rows returned
     * @throws DAOException
     */
    //27
    public int countUsingTemplate(ExpenseInvoiceItemBean bean) throws DAOException
    {
        return this.countUsingTemplate(bean, -1, -1);
    }

    /**
     * count the number of elements of a specific ExpenseInvoiceItemBean bean , given the start row and number of rows.
     *
     * @param bean the ExpenseInvoiceItemBean template to look for and count
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return the number of rows returned
     * @throws DAOException
     */
    //20
    public int countUsingTemplate(ExpenseInvoiceItemBean bean, int startRow, int numRows) throws DAOException
    {
        return this.countUsingTemplate(bean, startRow, numRows, SEARCH_EXACT);
    }

    /**
     * count the number of elements of a specific ExpenseInvoiceItemBean bean given the start row and number of rows and the search type
     *
     * @param bean the ExpenseInvoiceItemBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param searchType exact ?  like ? starting like ?
     * @return the number of rows returned
     * @throws DAOException
     */
    //20
    public int countUsingTemplate(ExpenseInvoiceItemBean bean, int startRow, int numRows, int searchType) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = new StringBuffer("SELECT COUNT(*) AS MCOUNT FROM expense_invoice_item");
        StringBuffer sqlWhere = new StringBuffer("");

        try
        {
            if (this.fillWhere(sqlWhere, bean, SEARCH_EXACT) > 0) {
                sql.append(" WHERE ").append(sqlWhere);
            } else {
                // System.out.println("The bean to look is not initialized... counting all...");
            }
            // System.out.println("countUsingTemplate: " + sql.toString());

            c = this.getConnection();
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, searchType);

            return this.countByPreparedStatement(ps);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }

    //


    /**
     * fills the given stringbuffer with the sql where clausis constructed using the bean and the search type
     * @param sqlWhere the stringbuffer that will be filled
     * @param bean the bean to use for creating the where clausis
     * @param searchType exact ?  like ? starting like ?
     * @return the number of clausis returned
     */
    protected int fillWhere(StringBuffer sqlWhere, ExpenseInvoiceItemBean bean, int searchType)
    {
        if (bean == null) {
            return 0;
        }
        int _dirtyCount = 0;
        String sqlEqualsOperation = "=";
        if (searchType != SEARCH_EXACT) {
            sqlEqualsOperation = " like ";
        }
        try
        {
            if (bean.isLastUpdateModified()) {
                _dirtyCount ++;
                if (bean.getLastUpdate() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("last_update IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("last_update = ?");
                }
            }
            if (bean.isInvoiceIdModified()) {
                _dirtyCount ++;
                if (bean.getInvoiceId() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("invoice_id IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("invoice_id = ?");
                }
            }
            if (bean.isHoursBilledModified()) {
                _dirtyCount ++;
                if (bean.getHoursBilled() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("hours_billed IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("hours_billed = ?");
                }
            }
            if (bean.isExpenseDescriptionModified()) {
                _dirtyCount ++;
                if (bean.getExpenseDescription() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("expense_description IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("expense_description ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isExpenseDateModified()) {
                _dirtyCount ++;
                if (bean.getExpenseDate() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("expense_date IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("expense_date = ?");
                }
            }
            if (bean.isExpenseInvoiceItemIdModified()) {
                _dirtyCount ++;
                if (bean.getExpenseInvoiceItemId() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("expense_invoice_item_id IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("expense_invoice_item_id = ?");
                }
            }
        }
        finally
        {
            sqlEqualsOperation = null;
        }
        return _dirtyCount;
    }

    /**
     * fill the given prepared statement with the bean values and a search type
     * @param ps the preparedStatement that will be filled
     * @param bean the bean to use for creating the where clausis
     * @param searchType exact ?  like ? starting like ?
     * @return the number of clausis returned
     * @throws DAOException
     */
    protected int fillPreparedStatement(PreparedStatement ps, ExpenseInvoiceItemBean bean, int searchType) throws DAOException
    {
        if (bean == null) {
            return 0;
        }
        int _dirtyCount = 0;
        try
        {
            if (bean.isLastUpdateModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getLastUpdate() + "]");
                if (bean.getLastUpdate() == null) { ps.setNull(++_dirtyCount, Types.TIMESTAMP); } else { ps.setTimestamp(++_dirtyCount, new java.sql.Timestamp(bean.getLastUpdate().getTime())); }
            }
            if (bean.isInvoiceIdModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getInvoiceId() + "]");
                if (bean.getInvoiceId() == null) { ps.setNull(++_dirtyCount, Types.INTEGER); } else { Manager.setInteger(ps, ++_dirtyCount, bean.getInvoiceId()); }
            }
            if (bean.isHoursBilledModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getHoursBilled() + "]");
                if (bean.getHoursBilled() == null) { ps.setNull(++_dirtyCount, Types.DOUBLE); } else { Manager.setDouble(ps, ++_dirtyCount, bean.getHoursBilled()); }
            }
            if (bean.isExpenseDescriptionModified()) {
                switch (searchType){
                    case SEARCH_EXACT:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getExpenseDescription() + "]");
                        if (bean.getExpenseDescription() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getExpenseDescription()); }
                        break;
                    case SEARCH_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getExpenseDescription() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getExpenseDescription() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getExpenseDescription() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getExpenseDescription());
                        break;
                    case SEARCH_ENDING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getExpenseDescription() + "]");
                        if (bean.getExpenseDescription() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getExpenseDescription() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isExpenseDateModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getExpenseDate() + "]");
                if (bean.getExpenseDate() == null) { ps.setNull(++_dirtyCount, Types.DATE); } else { ps.setDate(++_dirtyCount, new java.sql.Date(bean.getExpenseDate().getTime())); }
            }
            if (bean.isExpenseInvoiceItemIdModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getExpenseInvoiceItemId() + "]");
                if (bean.getExpenseInvoiceItemId() == null) { ps.setNull(++_dirtyCount, Types.INTEGER); } else { Manager.setInteger(ps, ++_dirtyCount, bean.getExpenseInvoiceItemId()); }
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        return _dirtyCount;
    }


    //_____________________________________________________________________
    //
    // DECODE RESULT SET
    //_____________________________________________________________________

    /**
     * decode a resultset in an array of ExpenseInvoiceItemBean objects
     *
     * @param rs the resultset to decode
     * @param fieldList table of the field's associated constants
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return the resulting ExpenseInvoiceItemBean table
     * @throws DAOException
     */
    //28
    public ExpenseInvoiceItemBean[] decodeResultSet(ResultSet rs, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        List v = new ArrayList();
        try
        {
            if (rs.absolute(startRow) && numRows!=0)
            {
                int count = 0;
                if(fieldList == null) {
                    do
                    {
                        v.add(decodeRow(rs));
                        count++;
                    } while ( (count<numRows||numRows<0) && rs.next() );
                }
                else {
                    do
                    {
                        v.add(decodeRow(rs, fieldList));
                        count++;
                    } while ( (count<numRows||numRows<0) && rs.next() );
                }
            }
            return (ExpenseInvoiceItemBean[])v.toArray(new ExpenseInvoiceItemBean[v.size()]);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            if (v != null) { v.clear(); v = null;}
        }
    }

    /**
     * Transforms a ResultSet iterating on the expense_invoice_item on a ExpenseInvoiceItemBean bean.
     *
     * @param rs the ResultSet to be transformed
     * @return bean resulting ExpenseInvoiceItemBean bean
     * @throws DAOException
     */
    //29
    public ExpenseInvoiceItemBean decodeRow(ResultSet rs) throws DAOException
    {
        ExpenseInvoiceItemBean bean = this.createExpenseInvoiceItemBean();
        try
        {
            bean.setLastUpdate(rs.getTimestamp(1));
            bean.setInvoiceId(Manager.getInteger(rs, 2));
            bean.setHoursBilled(Manager.getDouble(rs, 3));
            bean.setExpenseDescription(rs.getString(4));
            bean.setExpenseDate(rs.getDate(5));
            bean.setExpenseInvoiceItemId(Manager.getInteger(rs, 6));
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    /**
     * Transforms a ResultSet iterating on the expense_invoice_item table on a ExpenseInvoiceItemBean bean according to a list of fields.
     *
     * @param rs the ResultSet to be transformed
     * @param fieldList table of the field's associated constants
     * @return bean resulting ExpenseInvoiceItemBean bean
     * @throws DAOException
     */
    //30
    public ExpenseInvoiceItemBean decodeRow(ResultSet rs, int[] fieldList) throws DAOException
    {
        ExpenseInvoiceItemBean bean = this.createExpenseInvoiceItemBean();
        int pos = 0;
        try
        {
            for(int i = 0; i < fieldList.length; i++)
            {
                switch(fieldList[i])
                {
                    case ID_LAST_UPDATE:
                        ++pos;
                        bean.setLastUpdate(rs.getTimestamp(pos));
                        break;
                    case ID_INVOICE_ID:
                        ++pos;
                        bean.setInvoiceId(Manager.getInteger(rs, pos));
                        break;
                    case ID_HOURS_BILLED:
                        ++pos;
                        bean.setHoursBilled(Manager.getDouble(rs, pos));
                        break;
                    case ID_EXPENSE_DESCRIPTION:
                        ++pos;
                        bean.setExpenseDescription(rs.getString(pos));
                        break;
                    case ID_EXPENSE_DATE:
                        ++pos;
                        bean.setExpenseDate(rs.getDate(pos));
                        break;
                    case ID_EXPENSE_INVOICE_ITEM_ID:
                        ++pos;
                        bean.setExpenseInvoiceItemId(Manager.getInteger(rs, pos));
                        break;
                    default:
                        throw new DAOException("Unknown field id " + fieldList[i]);
                }
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    /**
     * Transforms a ResultSet iterating on the expense_invoice_item on a ExpenseInvoiceItemBean bean using the names of the columns
     *
     * @param rs the ResultSet to be transformed
     * @return bean resulting ExpenseInvoiceItemBean bean
     * @throws DAOException
     */
    //31
    public ExpenseInvoiceItemBean metaDataDecodeRow(ResultSet rs) throws DAOException
    {
        ExpenseInvoiceItemBean bean = this.createExpenseInvoiceItemBean();
        try
        {
            bean.setLastUpdate(rs.getTimestamp("last_update"));
            bean.setInvoiceId(Manager.getInteger(rs, "invoice_id"));
            bean.setHoursBilled(Manager.getDouble(rs, "hours_billed"));
            bean.setExpenseDescription(rs.getString("expense_description"));
            bean.setExpenseDate(rs.getDate("expense_date"));
            bean.setExpenseInvoiceItemId(Manager.getInteger(rs, "expense_invoice_item_id"));
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }

        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    //////////////////////////////////////
    // PREPARED STATEMENT LOADER
    //////////////////////////////////////

    /**
     * Loads all the elements using a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return an array of ExpenseInvoiceItemBean
     * @throws DAOException
     */
    //32
    public ExpenseInvoiceItemBean[] loadByPreparedStatement(PreparedStatement ps) throws DAOException
    {
        return this.loadByPreparedStatement(ps, null);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved.
     *
     * @param ps the PreparedStatement to be used
     * @param fieldList table of the field's associated constants
     * @return an array of ExpenseInvoiceItemBean
     * @throws DAOException
     */
    //33
    public ExpenseInvoiceItemBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList) throws DAOException
    {
        ResultSet rs =  null;
		List v =  null;
		try
		{
		    rs =  ps.executeQuery();
		    v = new ArrayList();
			if(fieldList == null) {
				while(rs.next()) {
					v.add(decodeRow(rs));
				}
			}
			else {
				while(rs.next()) {
					v.add(decodeRow(rs, fieldList));
				}
			}

			return (ExpenseInvoiceItemBean[])v.toArray(new ExpenseInvoiceItemBean[0]);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            if (v != null) { v.clear(); v = null;}
            getManager().close(rs);
        }
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved,
     * and specifying the start row and the number of rows.
     *
     * @param ps the PreparedStatement to be used
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return an array of ExpenseInvoiceItemBean
     * @throws DAOException
     */
    //34
    public ExpenseInvoiceItemBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        ResultSet rs =  null;
        try
        {
            rs = ps.executeQuery();
            return this.decodeResultSet(rs, fieldList, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(rs);
        }
    }

    //_____________________________________________________________________
    //
    // LISTENER
    //_____________________________________________________________________
    private ExpenseInvoiceItemListener listener = null;

    /**
     * Registers a unique ExpenseInvoiceItemListener listener.
     */
    //35
    public void registerListener(ExpenseInvoiceItemListener listener)
    {
        this.listener = listener;
    }

    /**
     * Before the save of the ExpenseInvoiceItemBean bean.
     *
     * @param bean the ExpenseInvoiceItemBean bean to be saved
     */
    //36
    private void beforeInsert(ExpenseInvoiceItemBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeInsert(bean);
        }
    }

    /**
     * After the save of the ExpenseInvoiceItemBean bean.
     *
     * @param bean the ExpenseInvoiceItemBean bean to be saved
     */
    //37
    private void afterInsert(ExpenseInvoiceItemBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterInsert(bean);
        }
    }

    /**
     * Before the update of the ExpenseInvoiceItemBean bean.
     *
     * @param bean the ExpenseInvoiceItemBean bean to be updated
     */
    //38
    private void beforeUpdate(ExpenseInvoiceItemBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeUpdate(bean);
        }
    }

    /**
     * After the update of the ExpenseInvoiceItemBean bean.
     *
     * @param bean the ExpenseInvoiceItemBean bean to be updated
     */
    //39
    private void afterUpdate(ExpenseInvoiceItemBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterUpdate(bean);
        }
    }

    /**
     * Before the delete of the ExpenseInvoiceItemBean bean.
     *
     * @param bean the ExpenseInvoiceItemBean bean to be deleted
     */
    private void beforeDelete(ExpenseInvoiceItemBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeDelete(bean);
        }
    }

    /**
     * After the delete of the ExpenseInvoiceItemBean bean.
     *
     * @param bean the ExpenseInvoiceItemBean bean to be deleted
     */
    private void afterDelete(ExpenseInvoiceItemBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterDelete(bean);
        }
    }

    //_____________________________________________________________________
    //
    // UTILS
    //_____________________________________________________________________

    /**
     * Retrieves the manager object used to get connections.
     *
     * @return the manager used
     */
    //40
    private Manager getManager()
    {
        return Manager.getInstance();
    }

    /**
     * Frees the connection.
     *
     * @param c the connection to release
     */
    //41
    private void freeConnection(Connection c)
    {
        this.getManager().releaseConnection(c); // back to pool
    }

    /**
     * Gets the connection.
     */
    //42
    private Connection getConnection() throws DAOException
    {
        try
        {
            return this.getManager().getConnection();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
    }
}
