// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package legaltime.model;

import java.util.Comparator;


/**
 * Comparator class is used to sort the PaymentLogBean objects.
 * @author sql2java
 */
public class PaymentLogComparator implements Comparator
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for PaymentLogComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new PaymentLogComparator(PaymentLogManager.ID_CLIENT_ACCOUNT_REGISTER_ID, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>PaymentLogManager.ID_CLIENT_ACCOUNT_REGISTER_ID
     *   <li>PaymentLogManager.ID_CLIENT_ID
     *   <li>PaymentLogManager.ID_INVOICE_ID
     *   <li>PaymentLogManager.ID_AMOUNT
     *   <li>PaymentLogManager.ID_DESCRIPTION
     *   <li>PaymentLogManager.ID_EFFECTIVE_DATE
     *   <li>PaymentLogManager.ID_PAYMENT_LOG_ID
     * </ul>
     */
    public PaymentLogComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for PaymentLogComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new PaymentLogComparator(PaymentLogManager.ID_CLIENT_ACCOUNT_REGISTER_ID, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>PaymentLogManager.ID_CLIENT_ACCOUNT_REGISTER_ID
     *   <li>PaymentLogManager.ID_CLIENT_ID
     *   <li>PaymentLogManager.ID_INVOICE_ID
     *   <li>PaymentLogManager.ID_AMOUNT
     *   <li>PaymentLogManager.ID_DESCRIPTION
     *   <li>PaymentLogManager.ID_EFFECTIVE_DATE
     *   <li>PaymentLogManager.ID_PAYMENT_LOG_ID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public PaymentLogComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        PaymentLogBean b1 = (PaymentLogBean)pObj1;
        PaymentLogBean b2 = (PaymentLogBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case PaymentLogManager.ID_CLIENT_ACCOUNT_REGISTER_ID:
                if (b1.getClientAccountRegisterId() == null && b2.getClientAccountRegisterId() != null) {
                    iReturn = -1;
                } else if (b1.getClientAccountRegisterId() == null && b2.getClientAccountRegisterId() == null) {
                    iReturn = 0;
                } else if (b1.getClientAccountRegisterId() != null && b2.getClientAccountRegisterId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getClientAccountRegisterId().compareTo(b2.getClientAccountRegisterId());
                }
                break;
            case PaymentLogManager.ID_CLIENT_ID:
                if (b1.getClientId() == null && b2.getClientId() != null) {
                    iReturn = -1;
                } else if (b1.getClientId() == null && b2.getClientId() == null) {
                    iReturn = 0;
                } else if (b1.getClientId() != null && b2.getClientId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getClientId().compareTo(b2.getClientId());
                }
                break;
            case PaymentLogManager.ID_INVOICE_ID:
                if (b1.getInvoiceId() == null && b2.getInvoiceId() != null) {
                    iReturn = -1;
                } else if (b1.getInvoiceId() == null && b2.getInvoiceId() == null) {
                    iReturn = 0;
                } else if (b1.getInvoiceId() != null && b2.getInvoiceId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getInvoiceId().compareTo(b2.getInvoiceId());
                }
                break;
            case PaymentLogManager.ID_AMOUNT:
                if (b1.getAmount() == null && b2.getAmount() != null) {
                    iReturn = -1;
                } else if (b1.getAmount() == null && b2.getAmount() == null) {
                    iReturn = 0;
                } else if (b1.getAmount() != null && b2.getAmount() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getAmount().compareTo(b2.getAmount());
                }
                break;
            case PaymentLogManager.ID_DESCRIPTION:
                if (b1.getDescription() == null && b2.getDescription() != null) {
                    iReturn = -1;
                } else if (b1.getDescription() == null && b2.getDescription() == null) {
                    iReturn = 0;
                } else if (b1.getDescription() != null && b2.getDescription() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getDescription().compareTo(b2.getDescription());
                }
                break;
            case PaymentLogManager.ID_EFFECTIVE_DATE:
                if (b1.getEffectiveDate() == null && b2.getEffectiveDate() != null) {
                    iReturn = -1;
                } else if (b1.getEffectiveDate() == null && b2.getEffectiveDate() == null) {
                    iReturn = 0;
                } else if (b1.getEffectiveDate() != null && b2.getEffectiveDate() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getEffectiveDate().compareTo(b2.getEffectiveDate());
                }
                break;
            case PaymentLogManager.ID_PAYMENT_LOG_ID:
                if (b1.getPaymentLogId() == null && b2.getPaymentLogId() != null) {
                    iReturn = -1;
                } else if (b1.getPaymentLogId() == null && b2.getPaymentLogId() == null) {
                    iReturn = 0;
                } else if (b1.getPaymentLogId() != null && b2.getPaymentLogId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getPaymentLogId().compareTo(b2.getPaymentLogId());
                }
                break;
            default:
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }}
