// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package legaltime.model;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;

import legaltime.model.Manager;
import legaltime.model.exception.DAOException;
import legaltime.model.exception.DataAccessException;
import legaltime.model.exception.ObjectRetrievalException;
import legaltime.model.ClientBean;
import legaltime.model.ClientManager;
import legaltime.model.InvoiceBean;
import legaltime.model.InvoiceManager;

/**
 * Handles database calls (save, load, count, etc...) for the payment_log table.
 * @author sql2java
 */
public class PaymentLogManager 
{

    /* set =QUERY for loadUsingTemplate */
    public static final int SEARCH_EXACT = 0;
    /* set %QUERY% for loadLikeTemplate */
    public static final int SEARCH_LIKE = 1;
    /* set %QUERY for loadLikeTemplate */
    public static final int SEARCH_STARTING_LIKE = 2;
    /* set QUERY% for loadLikeTemplate */
    public static final int SEARCH_ENDING_LIKE = 3;

    /**
     * Identify the client_id field.
     */
    public static final int ID_CLIENT_ID = 0;

    /**
     * Identify the invoice_id field.
     */
    public static final int ID_INVOICE_ID = 1;

    /**
     * Identify the amount field.
     */
    public static final int ID_AMOUNT = 2;

    /**
     * Identify the description field.
     */
    public static final int ID_DESCRIPTION = 3;

    /**
     * Identify the effective_date field.
     */
    public static final int ID_EFFECTIVE_DATE = 4;

    /**
     * Identify the payment_log_id field.
     */
    public static final int ID_PAYMENT_LOG_ID = 5;

    /**
     * Contains all the full fields of the payment_log table.
     */
    private static final String[] FULL_FIELD_NAMES =
    {
        "payment_log.client_id"
        ,"payment_log.invoice_id"
        ,"payment_log.amount"
        ,"payment_log.description"
        ,"payment_log.effective_date"
        ,"payment_log.payment_log_id"
    };

    /**
     * Contains all the fields of the payment_log table.
     */
    public static final String[] FIELD_NAMES =
    {
        "client_id"
        ,"invoice_id"
        ,"amount"
        ,"description"
        ,"effective_date"
        ,"payment_log_id"
    };

    /**
     * Field that contains the comma separated fields of the payment_log table.
     */
    public static final String ALL_FULL_FIELDS = "payment_log.client_id"
                            + ",payment_log.invoice_id"
                            + ",payment_log.amount"
                            + ",payment_log.description"
                            + ",payment_log.effective_date"
                            + ",payment_log.payment_log_id";

    /**
     * Field that contains the comma separated fields of the payment_log table.
     */
    public static final String ALL_FIELDS = "client_id"
                            + ",invoice_id"
                            + ",amount"
                            + ",description"
                            + ",effective_date"
                            + ",payment_log_id";

    private static PaymentLogManager singleton = new PaymentLogManager();

    /**
     * Get the PaymentLogManager singleton.
     *
     * @return PaymentLogManager
     */
    public static PaymentLogManager getInstance()
    {
        return singleton;
    }


    /**
     * Creates a new PaymentLogBean instance.
     *
     * @return the new PaymentLogBean
     */
    public PaymentLogBean createPaymentLogBean()
    {
        return new PaymentLogBean();
    }

    //////////////////////////////////////
    // PRIMARY KEY METHODS
    //////////////////////////////////////

    /**
     * Loads a PaymentLogBean from the payment_log using its key fields.
     *
     * @param paymentLogId Integer - PK# 1
     * @return a unique PaymentLogBean
     * @throws DAOException
     */
    //1
    public PaymentLogBean loadByPrimaryKey(Integer paymentLogId) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = this.getConnection();
            StringBuffer sql = new StringBuffer("SELECT " + ALL_FIELDS + " FROM payment_log WHERE payment_log_id=?");
            // System.out.println("loadByPrimaryKey: " + sql);
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            if (paymentLogId == null) { ps.setNull(1, Types.INTEGER); } else { Manager.setInteger(ps, 1, paymentLogId); }
            PaymentLogBean pReturn[] = this.loadByPreparedStatement(ps);
            if (pReturn.length < 1) {
                throw new ObjectRetrievalException();
            } else {
                return pReturn[0];
            }
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Deletes rows according to its keys.
     *
     * @param paymentLogId Integer - PK# 1
     * @return the number of deleted rows
     * @throws DAOException
     */
    //2
    public int deleteByPrimaryKey(Integer paymentLogId) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = this.getConnection();
            StringBuffer sql = new StringBuffer("DELETE FROM payment_log WHERE payment_log_id=?");
            // System.out.println("deleteByPrimaryKey: " + sql);
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            if (paymentLogId == null) { ps.setNull(1, Types.INTEGER); } else { Manager.setInteger(ps, 1, paymentLogId); }
            return ps.executeUpdate();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }


    //////////////////////////////////////
    // GET/SET FOREIGN KEY BEAN METHOD
    //////////////////////////////////////
    /**
     * Retrieves the ClientBean object from the payment_log.client_id field.
     *
     * @param bean the PaymentLogBean
     * @return the associated ClientBean bean
     * @throws DAOException
     */
    //3.2 GET IMPORTED VALUES
    public ClientBean getClientBean(PaymentLogBean bean) throws DAOException
    {
        ClientBean other = ClientManager.getInstance().createClientBean();
        other.setClientId(bean.getClientId()); 
        bean.setClientBean(ClientManager.getInstance().loadUniqueUsingTemplate(other)); 
        return bean.getClientBean();
    }

    /**
     * Associates the PaymentLogBean object to the ClientBean object.
     *
     * @param bean the PaymentLogBean object to use
     * @param beanToSet the ClientBean object to associate to the PaymentLogBean
     * @return the associated ClientBean bean
     * @throws Exception
     */
    //4.2 ADD IMPORTED VALUE
    public ClientBean addClientBean(ClientBean beanToSet, PaymentLogBean bean) throws Exception
    {
        beanToSet.setClientId(bean.getClientId());
        return ClientManager.getInstance().save(beanToSet);
    }

    /**
     * Associates the PaymentLogBean object to the ClientBean object.
     *
     * @param bean the PaymentLogBean object to use
     * @param beanToSet the ClientBean object to associate to the PaymentLogBean
     * @return the associated ClientBean bean
     * @throws Exception
     */
    //5.2 SET IMPORTED
    public ClientBean setClientBean(PaymentLogBean bean, ClientBean beanToSet) throws Exception
    {
        bean.setClientId(beanToSet.getClientId());
        return ClientManager.getInstance().save(beanToSet);
    }

    /**
     * Retrieves the InvoiceBean object from the payment_log.invoice_id field.
     *
     * @param bean the PaymentLogBean
     * @return the associated InvoiceBean bean
     * @throws DAOException
     */
    //3.2 GET IMPORTED VALUES
    public InvoiceBean getInvoiceBean(PaymentLogBean bean) throws DAOException
    {
        InvoiceBean other = InvoiceManager.getInstance().createInvoiceBean();
        other.setInvoiceId(bean.getInvoiceId()); 
        bean.setInvoiceBean(InvoiceManager.getInstance().loadUniqueUsingTemplate(other)); 
        return bean.getInvoiceBean();
    }

    /**
     * Associates the PaymentLogBean object to the InvoiceBean object.
     *
     * @param bean the PaymentLogBean object to use
     * @param beanToSet the InvoiceBean object to associate to the PaymentLogBean
     * @return the associated InvoiceBean bean
     * @throws Exception
     */
    //4.2 ADD IMPORTED VALUE
    public InvoiceBean addInvoiceBean(InvoiceBean beanToSet, PaymentLogBean bean) throws Exception
    {
        beanToSet.setInvoiceId(bean.getInvoiceId());
        return InvoiceManager.getInstance().save(beanToSet);
    }

    /**
     * Associates the PaymentLogBean object to the InvoiceBean object.
     *
     * @param bean the PaymentLogBean object to use
     * @param beanToSet the InvoiceBean object to associate to the PaymentLogBean
     * @return the associated InvoiceBean bean
     * @throws Exception
     */
    //5.2 SET IMPORTED
    public InvoiceBean setInvoiceBean(PaymentLogBean bean, InvoiceBean beanToSet) throws Exception
    {
        bean.setInvoiceId(beanToSet.getInvoiceId());
        return InvoiceManager.getInstance().save(beanToSet);
    }



    //////////////////////////////////////
    // LOAD ALL
    //////////////////////////////////////

    /**
     * Loads all the rows from payment_log.
     *
     * @return an array of PaymentLogManager bean
     * @throws DAOException
     */
    //5
    public PaymentLogBean[] loadAll() throws DAOException
    {
        return this.loadUsingTemplate(null);
    }

    /**
     * Loads all the rows from payment_log.
     *
     * @param orderBy orders the beans
     * @return an array of PaymentLogManager bean
     * @throws DAOException
     */
    //5
    public PaymentLogBean[] loadAll(String orderBy) throws DAOException
    {
        return this.loadUsingTemplate(null, orderBy);
    }




    /**
     * Loads the given number of rows from payment_log, given the start row.
     *
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return an array of PaymentLogManager bean
     * @throws DAOException
     */
    //6
    public PaymentLogBean[] loadAll(int startRow, int numRows) throws DAOException
    {
        return this.loadUsingTemplate(null, startRow, numRows);
    }

    //////////////////////////////////////
    // SQL 'WHERE' METHOD
    //////////////////////////////////////
    /**
     * Retrieves an array of PaymentLogBean given a sql 'where' clause.
     *
     * @param where the sql 'where' clause
     * @return the resulting PaymentLogBean table
     * @throws DAOException
     */
    //7
    public PaymentLogBean[] loadByWhere(String where) throws DAOException
    {
        return this.loadByWhere(where, null);
    }

    /**
     * Retrieves an array of PaymentLogBean given a sql where clause, and a list of fields.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'WHERE' clause
     * @param fieldList array of field's ID
     * @return the resulting PaymentLogBean table
     * @throws DAOException
     */
    //8
    public PaymentLogBean[] loadByWhere(String where, int[] fieldList) throws DAOException
    {
        return this.loadByWhere(where, fieldList, 1, -1);
    }

    /**
     * Retrieves an array of PaymentLogBean given a sql where clause and a list of fields, and startRow and numRows.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'where' clause
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return the resulting PaymentLogBean table
     * @throws DAOException
     */
    //9
    public PaymentLogBean[] loadByWhere(String where, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        StringBuffer sql = new StringBuffer(128);
        if(fieldList == null) {
            sql.append("SELECT ").append(ALL_FIELDS).append(" FROM payment_log ").append(where);
        } else
        {
            sql.append("SELECT ");
            for(int i = 0; i < fieldList.length; i++)
            {
                if(i != 0) {
                    sql.append(",");
                }
                sql.append(FULL_FIELD_NAMES[fieldList[i]]);
            }
            sql.append(" FROM payment_log ");
            sql.append(where);
        }
        Connection c = null;
        Statement st = null;
        ResultSet rs =  null;
        // System.out.println("loadByWhere: " + sql);
        try
        {
            c = this.getConnection();
            st = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = st.executeQuery(sql.toString());
            return this.decodeResultSet(rs, fieldList, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(st, rs);
            this.freeConnection(c);
        }
    }


    /**
     * Deletes all rows from payment_log table.
     * @return the number of deleted rows.
     * @throws DAOException
     */
    //10
    public int deleteAll() throws DAOException
    {
        return this.deleteByWhere("");
    }


    /**
     * Deletes rows from the payment_log table using a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     * <br>Attention, if 'WHERE' is omitted it will delete all records.
     *
     * @param where the sql 'where' clause
     * @return the number of deleted rows
     * @throws DAOException
     */
    //11
    public int deleteByWhere(String where) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;

        try
        {
            c = this.getConnection();
            StringBuffer sql = new StringBuffer("DELETE FROM payment_log " + where);
            // System.out.println("deleteByWhere: " + sql);
            ps = c.prepareStatement(sql.toString());
            return ps.executeUpdate();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    //_____________________________________________________________________
    //
    // SAVE
    //_____________________________________________________________________
    /**
     * Saves the PaymentLogBean bean into the database.
     *
     * @param bean the PaymentLogBean bean to be saved
     * @return the inserted or updated bean
     * @throws DAOException
     */
    //12
    public PaymentLogBean save(PaymentLogBean bean) throws DAOException
    {
        if (bean.isNew()) {
            return this.insert(bean);
        } else {
            return this.update(bean);
        }
    }

    /**
     * Insert the PaymentLogBean bean into the database.
     *
     * @param bean the PaymentLogBean bean to be saved
     * @return the inserted bean
     * @throws DAOException
     */
    //13
    public PaymentLogBean insert(PaymentLogBean bean) throws DAOException
    {
        // mini checks
        if (!bean.isModified()) {
            return bean; // should not we log something ?
        }
        if (!bean.isNew()){
            return this.update(bean);
        }

        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = null;

        try
        {
            c = this.getConnection();
            this.beforeInsert(bean); // listener callback
            int _dirtyCount = 0;
            sql = new StringBuffer("INSERT into payment_log (");

            if (bean.isClientIdModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("client_id");
                _dirtyCount++;
            }

            if (bean.isInvoiceIdModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("invoice_id");
                _dirtyCount++;
            }

            if (bean.isAmountModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("amount");
                _dirtyCount++;
            }

            if (bean.isDescriptionModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("description");
                _dirtyCount++;
            }

            if (bean.isEffectiveDateModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("effective_date");
                _dirtyCount++;
            }

            if (bean.isPaymentLogIdModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("payment_log_id");
                _dirtyCount++;
            }

            sql.append(") values (");
            if(_dirtyCount > 0) {
                sql.append("?");
                for(int i = 1; i < _dirtyCount; i++) {
                    sql.append(",?");
                }
            }
            sql.append(")");


            // System.out.println("insert : " + sql.toString());

            ps = c.prepareStatement(sql.toString(), ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

            this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            ps.executeUpdate();

            if (!bean.isPaymentLogIdModified())
            {
                PreparedStatement ps2 = null;
                ResultSet rs = null;
                try {
                    ps2 = c.prepareStatement("SELECT last_insert_id()");
                    rs = ps2.executeQuery();
                    if(rs.next()) {
                        bean.setPaymentLogId(Manager.getInteger(rs, 1));
                    } else {
                        this.getManager().log("ATTENTION: Could not retrieve generated key!");
                    }
                } finally {
                    this.getManager().close(ps2, rs);
                }
            }

            bean.isNew(false);
            bean.resetIsModified();
            this.afterInsert(bean); // listener callback
            return bean;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Update the PaymentLogBean bean record in the database according to the changes.
     *
     * @param bean the PaymentLogBean bean to be updated
     * @return the updated bean
     * @throws DAOException
     */
    //14
    public PaymentLogBean update(PaymentLogBean bean) throws DAOException
    {
        // mini checks
        if (!bean.isModified()) {
            return bean; // should not we log something ?
        }
        if (bean.isNew()){
            return this.insert(bean);
        }

        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = null;

        try
        {
            c = this.getConnection();

            this.beforeUpdate(bean); // listener callback
            sql = new StringBuffer("UPDATE payment_log SET ");
            boolean useComma=false;

            if (bean.isClientIdModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("client_id=?");
            }

            if (bean.isInvoiceIdModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("invoice_id=?");
            }

            if (bean.isAmountModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("amount=?");
            }

            if (bean.isDescriptionModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("description=?");
            }

            if (bean.isEffectiveDateModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("effective_date=?");
            }

            if (bean.isPaymentLogIdModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("payment_log_id=?");
            }
            sql.append(" WHERE ");
            sql.append("payment_log_id=?");
            // System.out.println("update : " + sql.toString());
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);

            int _dirtyCount = this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            if (_dirtyCount == 0) {
                // System.out.println("The bean to look is not initialized... do not update.");
                return bean;
            }

            if (bean.getPaymentLogId() == null) { ps.setNull(++_dirtyCount, Types.INTEGER); } else { Manager.setInteger(ps, ++_dirtyCount, bean.getPaymentLogId()); }
            ps.executeUpdate();
            bean.resetIsModified();
            this.afterUpdate(bean); // listener callback

            return bean;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Saves an array of PaymentLogBean beans into the database.
     *
     * @param beans the PaymentLogBean bean table to be saved
     * @return the saved PaymentLogBean array.
     * @throws DAOException
     */
    //15
    public PaymentLogBean[] save(PaymentLogBean[] beans) throws DAOException
    {
        for (int iIndex = 0; iIndex < beans.length; iIndex ++)
        {
            this.save(beans[iIndex]);
        }
        return beans;
    }

    /**
     * Insert an array of PaymentLogBean beans into the database.
     *
     * @param beans the PaymentLogBean bean table to be inserted
     * @return the saved PaymentLogBean array.
     * @throws DAOException
     */
    //16
    public PaymentLogBean[] insert(PaymentLogBean[] beans) throws DAOException
    {
        return this.save(beans);
    }

    /**
     * Updates an array of PaymentLogBean beans into the database.
     *
     * @param beans the PaymentLogBean bean table to be inserted
     * @return the saved PaymentLogBean array.
     * @throws DAOException
     */
    //17
    public PaymentLogBean[] update(PaymentLogBean[] beans) throws DAOException
    {
        return this.save(beans);
    }



    //_____________________________________________________________________
    //
    // USING TEMPLATE
    //_____________________________________________________________________

 /**
     * Loads a unique PaymentLogBean bean from a template one giving a c
     *
     * @param bean the PaymentLogBean bean to look for
     * @return the bean matching the template
     * @throws DAOException
     */
    //18
    public PaymentLogBean loadUniqueUsingTemplate(PaymentLogBean bean) throws DAOException
    {
	return loadUniqueUsingTemplate(bean, "");

    }
    /**
     * Loads a unique PaymentLogBean bean from a template one giving a c
     *
     * @param bean the PaymentLogBean bean to look for
     * @param orderBy the order by clause for the list
     * @return the bean matching the template
     * @throws DAOException
     */
    //18
    public PaymentLogBean loadUniqueUsingTemplate(PaymentLogBean bean, String orderBy) throws DAOException
    {
         PaymentLogBean[] beans = this.loadUsingTemplate(bean,orderBy);
         if (beans.length == 0) {
             return null;
         }
         if (beans.length > 1) {
             throw new ObjectRetrievalException("More than one element !!");
         }
         return beans[0];
     }


     /**
     * Loads an array of PaymentLogBean from a template one.
     *
     * @param bean the PaymentLogBean template to look for
     * @return all the PaymentLogBean matching the template
     * @throws DAOException
     */
    //19
    public PaymentLogBean[] loadUsingTemplate(PaymentLogBean bean) throws DAOException
    {
        return this.loadUsingTemplate(bean, 1, -1, "");
    }

    /**
     * Loads an array of PaymentLogBean from a template one.
     *
     * @param bean the PaymentLogBean template to look for
     * @param orderBy the orderby clause for sql
     * @return all the PaymentLogBean matching the template
     * @throws DAOException
     */
    //19
    public PaymentLogBean[] loadUsingTemplate(PaymentLogBean bean, String orderBy) throws DAOException
    {
        return this.loadUsingTemplate(bean, 1, -1, orderBy);
    }


     /**
     * Loads an array of PaymentLogBean from a template one, given the start row and number of rows.
     *
     * @param bean the PaymentLogBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param orderBy SQL order by Clause
     * @return all the PaymentLogBean matching the template
     * @throws DAOException
     */
    //20
    public PaymentLogBean[] loadUsingTemplate(PaymentLogBean bean, int startRow, int numRows, String orderBy) throws DAOException
    {
        return this.loadUsingTemplate(bean, startRow, numRows, SEARCH_EXACT, orderBy);
    }


    /**
     * Loads an array of PaymentLogBean from a template one, given the start row and number of rows.
     *
     * @param bean the PaymentLogBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return all the PaymentLogBean matching the template
     * @throws DAOException
     */
    //20
    public PaymentLogBean[] loadUsingTemplate(PaymentLogBean bean, int startRow, int numRows) throws DAOException
    {
        return this.loadUsingTemplate(bean, startRow, numRows, SEARCH_EXACT,"");
    }

    /**
     * Loads an array of PaymentLogBean from a template one, given the start row and number of rows.
     *
     * @param bean the PaymentLogBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param searchType exact ?  like ? starting like ?
     * @param orderBy SQL orderBy Clause
     * @return all the PaymentLogBean matching the template
     * @throws DAOException
     */
    //20
    public PaymentLogBean[] loadUsingTemplate(PaymentLogBean bean, int startRow, int numRows, int searchType, String orderBy) throws DAOException
    {
        // System.out.println("loadUsingTemplate startRow:" + startRow + ", numRows:" + numRows + ", searchType:" + searchType);
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = new StringBuffer(128);
        sql.append("SELECT ").append(ALL_FIELDS).append(" FROM payment_log ");
        StringBuffer sqlWhere = new StringBuffer("");

        try
        {
            if (this.fillWhere(sqlWhere, bean, searchType) > 0) {
                sql.append(" WHERE ").append(sqlWhere);
            } else {
               // System.out.println("The bean to look is not initialized... loading all");
            }
            // System.out.println("loadUsingTemplate: " + sql.toString());
	    sql.append(" " + orderBy);

            c = this.getConnection();
            int scrollType = ResultSet.TYPE_SCROLL_INSENSITIVE;
            if (startRow != 1) {
                scrollType = ResultSet.TYPE_SCROLL_SENSITIVE;
            }
            ps = c.prepareStatement(sql.toString(),
                                    scrollType,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, searchType);

            ps.executeQuery();
            return this.loadByPreparedStatement(ps, null, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }

    /**
     * Deletes rows using a PaymentLogBean template.
     *
     * @param bean the PaymentLogBean object(s) to be deleted
     * @return the number of deleted objects
     * @throws DAOException
     */
    //21
    public int deleteUsingTemplate(PaymentLogBean bean) throws DAOException
    {
        if (bean.isPaymentLogIdInitialized()) {
            return this.deleteByPrimaryKey(bean.getPaymentLogId());
        }
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = new StringBuffer("DELETE FROM payment_log ");
        StringBuffer sqlWhere = new StringBuffer("");

        try
        {
            this.beforeDelete(bean); // listener callback
            if (this.fillWhere(sqlWhere, bean, SEARCH_EXACT) > 0) {
                sql.append(" WHERE ").append(sqlWhere);
            } else {
               // System.out.println("The bean to look is not initialized... deleting all");
            }
            // System.out.println("deleteUsingTemplate: " + sql.toString());

            c = this.getConnection();
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            int _rows = ps.executeUpdate();
            this.afterDelete(bean); // listener callback
            return _rows;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }


    //_____________________________________________________________________
    //
    // USING INDICES
    //_____________________________________________________________________

    /**
     * Retrieves an array of PaymentLogBean using the fk_invoice_paymentlog index.
     *
     * @param invoiceId the invoice_id column's value filter.
     * @return an array of PaymentLogBean
     * @throws DAOException
     */
    public PaymentLogBean[] loadByfk_invoice_paymentlog(Integer invoiceId) throws DAOException
    {
        PaymentLogBean bean = this.createPaymentLogBean();
        bean.setInvoiceId(invoiceId);
        return loadUsingTemplate(bean);
    }
    
    /**
     * Deletes rows using the fk_invoice_paymentlog index.
     *
     * @param invoiceId the invoice_id column's value filter.
     * @return the number of deleted objects
     * @throws DAOException
     */
    public int deleteByfk_invoice_paymentlog(Integer invoiceId) throws DAOException
    {
        PaymentLogBean bean = this.createPaymentLogBean();
        bean.setInvoiceId(invoiceId);
        return deleteUsingTemplate(bean);
    }
    
    /**
     * Retrieves an array of PaymentLogBean using the fk_client_paymentlog index.
     *
     * @param clientId the client_id column's value filter.
     * @return an array of PaymentLogBean
     * @throws DAOException
     */
    public PaymentLogBean[] loadByfk_client_paymentlog(Integer clientId) throws DAOException
    {
        PaymentLogBean bean = this.createPaymentLogBean();
        bean.setClientId(clientId);
        return loadUsingTemplate(bean);
    }
    
    /**
     * Deletes rows using the fk_client_paymentlog index.
     *
     * @param clientId the client_id column's value filter.
     * @return the number of deleted objects
     * @throws DAOException
     */
    public int deleteByfk_client_paymentlog(Integer clientId) throws DAOException
    {
        PaymentLogBean bean = this.createPaymentLogBean();
        bean.setClientId(clientId);
        return deleteUsingTemplate(bean);
    }
    


    //_____________________________________________________________________
    //
    // COUNT
    //_____________________________________________________________________

    /**
     * Retrieves the number of rows of the table payment_log.
     *
     * @return the number of rows returned
     * @throws DAOException
     */
    //24
    public int countAll() throws DAOException
    {
        return this.countWhere("");
    }

    /**
     * Retrieves the number of rows of the table payment_log with a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the restriction clause
     * @return the number of rows returned
     * @throws DAOException
     */
    //25
    public int countWhere(String where) throws DAOException
    {
        String sql = "SELECT COUNT(*) AS MCOUNT FROM payment_log " + where;
        // System.out.println("countWhere: " + sql);
        Connection c = null;
        Statement st = null;
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            c = this.getConnection();
            st = c.createStatement();
            rs =  st.executeQuery(sql);
            if (rs.next())
            {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1) {
                return iReturn;
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(st, rs);
            this.freeConnection(c);
            sql = null;
        }
        throw new DataAccessException("Error in countWhere where=[" + where + "]");
    }

    /**
     * Retrieves the number of rows of the table payment_log with a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return the number of rows returned
     * @throws DAOException
     */
    //26
    private int countByPreparedStatement(PreparedStatement ps) throws DAOException
    {
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            rs = ps.executeQuery();
            if (rs.next()) {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1) {
                return iReturn;
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(rs);
        }
       throw new DataAccessException("Error in countByPreparedStatement");
    }

    /**
     * count the number of elements of a specific PaymentLogBean bean
     *
     * @param bean the PaymentLogBean bean to look for ant count
     * @return the number of rows returned
     * @throws DAOException
     */
    //27
    public int countUsingTemplate(PaymentLogBean bean) throws DAOException
    {
        return this.countUsingTemplate(bean, -1, -1);
    }

    /**
     * count the number of elements of a specific PaymentLogBean bean , given the start row and number of rows.
     *
     * @param bean the PaymentLogBean template to look for and count
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return the number of rows returned
     * @throws DAOException
     */
    //20
    public int countUsingTemplate(PaymentLogBean bean, int startRow, int numRows) throws DAOException
    {
        return this.countUsingTemplate(bean, startRow, numRows, SEARCH_EXACT);
    }

    /**
     * count the number of elements of a specific PaymentLogBean bean given the start row and number of rows and the search type
     *
     * @param bean the PaymentLogBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param searchType exact ?  like ? starting like ?
     * @return the number of rows returned
     * @throws DAOException
     */
    //20
    public int countUsingTemplate(PaymentLogBean bean, int startRow, int numRows, int searchType) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = new StringBuffer("SELECT COUNT(*) AS MCOUNT FROM payment_log");
        StringBuffer sqlWhere = new StringBuffer("");

        try
        {
            if (this.fillWhere(sqlWhere, bean, SEARCH_EXACT) > 0) {
                sql.append(" WHERE ").append(sqlWhere);
            } else {
                // System.out.println("The bean to look is not initialized... counting all...");
            }
            // System.out.println("countUsingTemplate: " + sql.toString());

            c = this.getConnection();
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, searchType);

            return this.countByPreparedStatement(ps);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }

    //


    /**
     * fills the given stringbuffer with the sql where clausis constructed using the bean and the search type
     * @param sqlWhere the stringbuffer that will be filled
     * @param bean the bean to use for creating the where clausis
     * @param searchType exact ?  like ? starting like ?
     * @return the number of clausis returned
     */
    protected int fillWhere(StringBuffer sqlWhere, PaymentLogBean bean, int searchType)
    {
        if (bean == null) {
            return 0;
        }
        int _dirtyCount = 0;
        String sqlEqualsOperation = "=";
        if (searchType != SEARCH_EXACT) {
            sqlEqualsOperation = " like ";
        }
        try
        {
            if (bean.isClientIdModified()) {
                _dirtyCount ++;
                if (bean.getClientId() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("client_id IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("client_id = ?");
                }
            }
            if (bean.isInvoiceIdModified()) {
                _dirtyCount ++;
                if (bean.getInvoiceId() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("invoice_id IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("invoice_id = ?");
                }
            }
            if (bean.isAmountModified()) {
                _dirtyCount ++;
                if (bean.getAmount() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("amount IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("amount = ?");
                }
            }
            if (bean.isDescriptionModified()) {
                _dirtyCount ++;
                if (bean.getDescription() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("description IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("description ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isEffectiveDateModified()) {
                _dirtyCount ++;
                if (bean.getEffectiveDate() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("effective_date IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("effective_date = ?");
                }
            }
            if (bean.isPaymentLogIdModified()) {
                _dirtyCount ++;
                if (bean.getPaymentLogId() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("payment_log_id IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("payment_log_id = ?");
                }
            }
        }
        finally
        {
            sqlEqualsOperation = null;
        }
        return _dirtyCount;
    }

    /**
     * fill the given prepared statement with the bean values and a search type
     * @param ps the preparedStatement that will be filled
     * @param bean the bean to use for creating the where clausis
     * @param searchType exact ?  like ? starting like ?
     * @return the number of clausis returned
     * @throws DAOException
     */
    protected int fillPreparedStatement(PreparedStatement ps, PaymentLogBean bean, int searchType) throws DAOException
    {
        if (bean == null) {
            return 0;
        }
        int _dirtyCount = 0;
        try
        {
            if (bean.isClientIdModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getClientId() + "]");
                if (bean.getClientId() == null) { ps.setNull(++_dirtyCount, Types.INTEGER); } else { Manager.setInteger(ps, ++_dirtyCount, bean.getClientId()); }
            }
            if (bean.isInvoiceIdModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getInvoiceId() + "]");
                if (bean.getInvoiceId() == null) { ps.setNull(++_dirtyCount, Types.INTEGER); } else { Manager.setInteger(ps, ++_dirtyCount, bean.getInvoiceId()); }
            }
            if (bean.isAmountModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getAmount() + "]");
                if (bean.getAmount() == null) { ps.setNull(++_dirtyCount, Types.DOUBLE); } else { Manager.setDouble(ps, ++_dirtyCount, bean.getAmount()); }
            }
            if (bean.isDescriptionModified()) {
                switch (searchType){
                    case SEARCH_EXACT:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getDescription() + "]");
                        if (bean.getDescription() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getDescription()); }
                        break;
                    case SEARCH_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getDescription() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getDescription() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getDescription() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getDescription());
                        break;
                    case SEARCH_ENDING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getDescription() + "]");
                        if (bean.getDescription() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getDescription() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isEffectiveDateModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getEffectiveDate() + "]");
                if (bean.getEffectiveDate() == null) { ps.setNull(++_dirtyCount, Types.DATE); } else { ps.setDate(++_dirtyCount, new java.sql.Date(bean.getEffectiveDate().getTime())); }
            }
            if (bean.isPaymentLogIdModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getPaymentLogId() + "]");
                if (bean.getPaymentLogId() == null) { ps.setNull(++_dirtyCount, Types.INTEGER); } else { Manager.setInteger(ps, ++_dirtyCount, bean.getPaymentLogId()); }
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        return _dirtyCount;
    }


    //_____________________________________________________________________
    //
    // DECODE RESULT SET
    //_____________________________________________________________________

    /**
     * decode a resultset in an array of PaymentLogBean objects
     *
     * @param rs the resultset to decode
     * @param fieldList table of the field's associated constants
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return the resulting PaymentLogBean table
     * @throws DAOException
     */
    //28
    public PaymentLogBean[] decodeResultSet(ResultSet rs, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        List v = new ArrayList();
        try
        {
            if (rs.absolute(startRow) && numRows!=0)
            {
                int count = 0;
                if(fieldList == null) {
                    do
                    {
                        v.add(decodeRow(rs));
                        count++;
                    } while ( (count<numRows||numRows<0) && rs.next() );
                }
                else {
                    do
                    {
                        v.add(decodeRow(rs, fieldList));
                        count++;
                    } while ( (count<numRows||numRows<0) && rs.next() );
                }
            }
            return (PaymentLogBean[])v.toArray(new PaymentLogBean[v.size()]);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            if (v != null) { v.clear(); v = null;}
        }
    }

    /**
     * Transforms a ResultSet iterating on the payment_log on a PaymentLogBean bean.
     *
     * @param rs the ResultSet to be transformed
     * @return bean resulting PaymentLogBean bean
     * @throws DAOException
     */
    //29
    public PaymentLogBean decodeRow(ResultSet rs) throws DAOException
    {
        PaymentLogBean bean = this.createPaymentLogBean();
        try
        {
            bean.setClientId(Manager.getInteger(rs, 1));
            bean.setInvoiceId(Manager.getInteger(rs, 2));
            bean.setAmount(Manager.getDouble(rs, 3));
            bean.setDescription(rs.getString(4));
            bean.setEffectiveDate(rs.getDate(5));
            bean.setPaymentLogId(Manager.getInteger(rs, 6));
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    /**
     * Transforms a ResultSet iterating on the payment_log table on a PaymentLogBean bean according to a list of fields.
     *
     * @param rs the ResultSet to be transformed
     * @param fieldList table of the field's associated constants
     * @return bean resulting PaymentLogBean bean
     * @throws DAOException
     */
    //30
    public PaymentLogBean decodeRow(ResultSet rs, int[] fieldList) throws DAOException
    {
        PaymentLogBean bean = this.createPaymentLogBean();
        int pos = 0;
        try
        {
            for(int i = 0; i < fieldList.length; i++)
            {
                switch(fieldList[i])
                {
                    case ID_CLIENT_ID:
                        ++pos;
                        bean.setClientId(Manager.getInteger(rs, pos));
                        break;
                    case ID_INVOICE_ID:
                        ++pos;
                        bean.setInvoiceId(Manager.getInteger(rs, pos));
                        break;
                    case ID_AMOUNT:
                        ++pos;
                        bean.setAmount(Manager.getDouble(rs, pos));
                        break;
                    case ID_DESCRIPTION:
                        ++pos;
                        bean.setDescription(rs.getString(pos));
                        break;
                    case ID_EFFECTIVE_DATE:
                        ++pos;
                        bean.setEffectiveDate(rs.getDate(pos));
                        break;
                    case ID_PAYMENT_LOG_ID:
                        ++pos;
                        bean.setPaymentLogId(Manager.getInteger(rs, pos));
                        break;
                    default:
                        throw new DAOException("Unknown field id " + fieldList[i]);
                }
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    /**
     * Transforms a ResultSet iterating on the payment_log on a PaymentLogBean bean using the names of the columns
     *
     * @param rs the ResultSet to be transformed
     * @return bean resulting PaymentLogBean bean
     * @throws DAOException
     */
    //31
    public PaymentLogBean metaDataDecodeRow(ResultSet rs) throws DAOException
    {
        PaymentLogBean bean = this.createPaymentLogBean();
        try
        {
            bean.setClientId(Manager.getInteger(rs, "client_id"));
            bean.setInvoiceId(Manager.getInteger(rs, "invoice_id"));
            bean.setAmount(Manager.getDouble(rs, "amount"));
            bean.setDescription(rs.getString("description"));
            bean.setEffectiveDate(rs.getDate("effective_date"));
            bean.setPaymentLogId(Manager.getInteger(rs, "payment_log_id"));
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }

        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    //////////////////////////////////////
    // PREPARED STATEMENT LOADER
    //////////////////////////////////////

    /**
     * Loads all the elements using a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return an array of PaymentLogBean
     * @throws DAOException
     */
    //32
    public PaymentLogBean[] loadByPreparedStatement(PreparedStatement ps) throws DAOException
    {
        return this.loadByPreparedStatement(ps, null);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved.
     *
     * @param ps the PreparedStatement to be used
     * @param fieldList table of the field's associated constants
     * @return an array of PaymentLogBean
     * @throws DAOException
     */
    //33
    public PaymentLogBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList) throws DAOException
    {
        ResultSet rs =  null;
		List v =  null;
		try
		{
		    rs =  ps.executeQuery();
		    v = new ArrayList();
			if(fieldList == null) {
				while(rs.next()) {
					v.add(decodeRow(rs));
				}
			}
			else {
				while(rs.next()) {
					v.add(decodeRow(rs, fieldList));
				}
			}

			return (PaymentLogBean[])v.toArray(new PaymentLogBean[0]);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            if (v != null) { v.clear(); v = null;}
            getManager().close(rs);
        }
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved,
     * and specifying the start row and the number of rows.
     *
     * @param ps the PreparedStatement to be used
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return an array of PaymentLogBean
     * @throws DAOException
     */
    //34
    public PaymentLogBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        ResultSet rs =  null;
        try
        {
            rs = ps.executeQuery();
            return this.decodeResultSet(rs, fieldList, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(rs);
        }
    }

    //_____________________________________________________________________
    //
    // LISTENER
    //_____________________________________________________________________
    private PaymentLogListener listener = null;

    /**
     * Registers a unique PaymentLogListener listener.
     */
    //35
    public void registerListener(PaymentLogListener listener)
    {
        this.listener = listener;
    }

    /**
     * Before the save of the PaymentLogBean bean.
     *
     * @param bean the PaymentLogBean bean to be saved
     */
    //36
    private void beforeInsert(PaymentLogBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeInsert(bean);
        }
    }

    /**
     * After the save of the PaymentLogBean bean.
     *
     * @param bean the PaymentLogBean bean to be saved
     */
    //37
    private void afterInsert(PaymentLogBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterInsert(bean);
        }
    }

    /**
     * Before the update of the PaymentLogBean bean.
     *
     * @param bean the PaymentLogBean bean to be updated
     */
    //38
    private void beforeUpdate(PaymentLogBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeUpdate(bean);
        }
    }

    /**
     * After the update of the PaymentLogBean bean.
     *
     * @param bean the PaymentLogBean bean to be updated
     */
    //39
    private void afterUpdate(PaymentLogBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterUpdate(bean);
        }
    }

    /**
     * Before the delete of the PaymentLogBean bean.
     *
     * @param bean the PaymentLogBean bean to be deleted
     */
    private void beforeDelete(PaymentLogBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeDelete(bean);
        }
    }

    /**
     * After the delete of the PaymentLogBean bean.
     *
     * @param bean the PaymentLogBean bean to be deleted
     */
    private void afterDelete(PaymentLogBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterDelete(bean);
        }
    }

    //_____________________________________________________________________
    //
    // UTILS
    //_____________________________________________________________________

    /**
     * Retrieves the manager object used to get connections.
     *
     * @return the manager used
     */
    //40
    private Manager getManager()
    {
        return Manager.getInstance();
    }

    /**
     * Frees the connection.
     *
     * @param c the connection to release
     */
    //41
    private void freeConnection(Connection c)
    {
        this.getManager().releaseConnection(c); // back to pool
    }

    /**
     * Gets the connection.
     */
    //42
    private Connection getConnection() throws DAOException
    {
        try
        {
            return this.getManager().getConnection();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
    }
}
