// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package legaltime.model;

import java.util.Comparator;


/**
 * Comparator class is used to sort the SysCodeBean objects.
 * @author sql2java
 */
public class SysCodeComparator implements Comparator
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for SysCodeComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new SysCodeComparator(SysCodeManager.ID_LAST_UPDATE, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>SysCodeManager.ID_LAST_UPDATE
     *   <li>SysCodeManager.ID_SYSTEM_OR_USER
     *   <li>SysCodeManager.ID_DESCRIPTION
     *   <li>SysCodeManager.ID_CODE_ID
     *   <li>SysCodeManager.ID_CODE_TYPE
     *   <li>SysCodeManager.ID_SYS_CODE_ID
     * </ul>
     */
    public SysCodeComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for SysCodeComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new SysCodeComparator(SysCodeManager.ID_LAST_UPDATE, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>SysCodeManager.ID_LAST_UPDATE
     *   <li>SysCodeManager.ID_SYSTEM_OR_USER
     *   <li>SysCodeManager.ID_DESCRIPTION
     *   <li>SysCodeManager.ID_CODE_ID
     *   <li>SysCodeManager.ID_CODE_TYPE
     *   <li>SysCodeManager.ID_SYS_CODE_ID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public SysCodeComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        SysCodeBean b1 = (SysCodeBean)pObj1;
        SysCodeBean b2 = (SysCodeBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case SysCodeManager.ID_LAST_UPDATE:
                if (b1.getLastUpdate() == null && b2.getLastUpdate() != null) {
                    iReturn = -1;
                } else if (b1.getLastUpdate() == null && b2.getLastUpdate() == null) {
                    iReturn = 0;
                } else if (b1.getLastUpdate() != null && b2.getLastUpdate() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getLastUpdate().compareTo(b2.getLastUpdate());
                }
                break;
            case SysCodeManager.ID_SYSTEM_OR_USER:
                if (b1.getSystemOrUser() == null && b2.getSystemOrUser() != null) {
                    iReturn = -1;
                } else if (b1.getSystemOrUser() == null && b2.getSystemOrUser() == null) {
                    iReturn = 0;
                } else if (b1.getSystemOrUser() != null && b2.getSystemOrUser() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getSystemOrUser().compareTo(b2.getSystemOrUser());
                }
                break;
            case SysCodeManager.ID_DESCRIPTION:
                if (b1.getDescription() == null && b2.getDescription() != null) {
                    iReturn = -1;
                } else if (b1.getDescription() == null && b2.getDescription() == null) {
                    iReturn = 0;
                } else if (b1.getDescription() != null && b2.getDescription() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getDescription().compareTo(b2.getDescription());
                }
                break;
            case SysCodeManager.ID_CODE_ID:
                if (b1.getCodeId() == null && b2.getCodeId() != null) {
                    iReturn = -1;
                } else if (b1.getCodeId() == null && b2.getCodeId() == null) {
                    iReturn = 0;
                } else if (b1.getCodeId() != null && b2.getCodeId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getCodeId().compareTo(b2.getCodeId());
                }
                break;
            case SysCodeManager.ID_CODE_TYPE:
                if (b1.getCodeType() == null && b2.getCodeType() != null) {
                    iReturn = -1;
                } else if (b1.getCodeType() == null && b2.getCodeType() == null) {
                    iReturn = 0;
                } else if (b1.getCodeType() != null && b2.getCodeType() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getCodeType().compareTo(b2.getCodeType());
                }
                break;
            case SysCodeManager.ID_SYS_CODE_ID:
                if (b1.getSysCodeId() == null && b2.getSysCodeId() != null) {
                    iReturn = -1;
                } else if (b1.getSysCodeId() == null && b2.getSysCodeId() == null) {
                    iReturn = 0;
                } else if (b1.getSysCodeId() != null && b2.getSysCodeId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getSysCodeId().compareTo(b2.getSysCodeId());
                }
                break;
            default:
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }}
