// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package legaltime.model;

import java.util.Comparator;


/**
 * Comparator class is used to sort the TranTypeBean objects.
 * @author sql2java
 */
public class TranTypeComparator implements Comparator
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for TranTypeComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new TranTypeComparator(TranTypeManager.ID_LAST_UPDATE, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>TranTypeManager.ID_LAST_UPDATE
     *   <li>TranTypeManager.ID_DESCRIPTION
     *   <li>TranTypeManager.ID_TRAN_TYPE
     *   <li>TranTypeManager.ID_TRAN_TYPE_ID
     * </ul>
     */
    public TranTypeComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for TranTypeComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new TranTypeComparator(TranTypeManager.ID_LAST_UPDATE, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>TranTypeManager.ID_LAST_UPDATE
     *   <li>TranTypeManager.ID_DESCRIPTION
     *   <li>TranTypeManager.ID_TRAN_TYPE
     *   <li>TranTypeManager.ID_TRAN_TYPE_ID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public TranTypeComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        TranTypeBean b1 = (TranTypeBean)pObj1;
        TranTypeBean b2 = (TranTypeBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case TranTypeManager.ID_LAST_UPDATE:
                if (b1.getLastUpdate() == null && b2.getLastUpdate() != null) {
                    iReturn = -1;
                } else if (b1.getLastUpdate() == null && b2.getLastUpdate() == null) {
                    iReturn = 0;
                } else if (b1.getLastUpdate() != null && b2.getLastUpdate() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getLastUpdate().compareTo(b2.getLastUpdate());
                }
                break;
            case TranTypeManager.ID_DESCRIPTION:
                if (b1.getDescription() == null && b2.getDescription() != null) {
                    iReturn = -1;
                } else if (b1.getDescription() == null && b2.getDescription() == null) {
                    iReturn = 0;
                } else if (b1.getDescription() != null && b2.getDescription() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getDescription().compareTo(b2.getDescription());
                }
                break;
            case TranTypeManager.ID_TRAN_TYPE:
                if (b1.getTranType() == null && b2.getTranType() != null) {
                    iReturn = -1;
                } else if (b1.getTranType() == null && b2.getTranType() == null) {
                    iReturn = 0;
                } else if (b1.getTranType() != null && b2.getTranType() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTranType().compareTo(b2.getTranType());
                }
                break;
            case TranTypeManager.ID_TRAN_TYPE_ID:
                if (b1.getTranTypeId() == null && b2.getTranTypeId() != null) {
                    iReturn = -1;
                } else if (b1.getTranTypeId() == null && b2.getTranTypeId() == null) {
                    iReturn = 0;
                } else if (b1.getTranTypeId() != null && b2.getTranTypeId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTranTypeId().compareTo(b2.getTranTypeId());
                }
                break;
            default:
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }}
