// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package legaltime.model;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;

import legaltime.model.Manager;
import legaltime.model.exception.DAOException;
import legaltime.model.exception.DataAccessException;
import legaltime.model.exception.ObjectRetrievalException;
import legaltime.model.ClientBillRateBean;
import legaltime.model.ClientBillRateManager;

/**
 * Handles database calls (save, load, count, etc...) for the user_info table.
 * @author sql2java
 */
public class UserInfoManager 
{

    /* set =QUERY for loadUsingTemplate */
    public static final int SEARCH_EXACT = 0;
    /* set %QUERY% for loadLikeTemplate */
    public static final int SEARCH_LIKE = 1;
    /* set %QUERY for loadLikeTemplate */
    public static final int SEARCH_STARTING_LIKE = 2;
    /* set QUERY% for loadLikeTemplate */
    public static final int SEARCH_ENDING_LIKE = 3;

    /**
     * Identify the last_update field.
     */
    public static final int ID_LAST_UPDATE = 0;

    /**
     * Identify the default_bill_rate field.
     */
    public static final int ID_DEFAULT_BILL_RATE = 1;

    /**
     * Identify the first_name field.
     */
    public static final int ID_FIRST_NAME = 2;

    /**
     * Identify the last_name field.
     */
    public static final int ID_LAST_NAME = 3;

    /**
     * Identify the user_key field.
     */
    public static final int ID_USER_KEY = 4;

    /**
     * Contains all the full fields of the user_info table.
     */
    private static final String[] FULL_FIELD_NAMES =
    {
        "user_info.last_update"
        ,"user_info.default_bill_rate"
        ,"user_info.first_name"
        ,"user_info.last_name"
        ,"user_info.user_key"
    };

    /**
     * Contains all the fields of the user_info table.
     */
    public static final String[] FIELD_NAMES =
    {
        "last_update"
        ,"default_bill_rate"
        ,"first_name"
        ,"last_name"
        ,"user_key"
    };

    /**
     * Field that contains the comma separated fields of the user_info table.
     */
    public static final String ALL_FULL_FIELDS = "user_info.last_update"
                            + ",user_info.default_bill_rate"
                            + ",user_info.first_name"
                            + ",user_info.last_name"
                            + ",user_info.user_key";

    /**
     * Field that contains the comma separated fields of the user_info table.
     */
    public static final String ALL_FIELDS = "last_update"
                            + ",default_bill_rate"
                            + ",first_name"
                            + ",last_name"
                            + ",user_key";

    private static UserInfoManager singleton = new UserInfoManager();

    /**
     * Get the UserInfoManager singleton.
     *
     * @return UserInfoManager
     */
    public static UserInfoManager getInstance()
    {
        return singleton;
    }


    /**
     * Creates a new UserInfoBean instance.
     *
     * @return the new UserInfoBean
     */
    public UserInfoBean createUserInfoBean()
    {
        return new UserInfoBean();
    }

    //////////////////////////////////////
    // PRIMARY KEY METHODS
    //////////////////////////////////////

    /**
     * Loads a UserInfoBean from the user_info using its key fields.
     *
     * @param userKey String - PK# 1
     * @return a unique UserInfoBean
     * @throws DAOException
     */
    //1
    public UserInfoBean loadByPrimaryKey(String userKey) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = this.getConnection();
            StringBuffer sql = new StringBuffer("SELECT " + ALL_FIELDS + " FROM user_info WHERE user_key=?");
            // System.out.println("loadByPrimaryKey: " + sql);
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            if (userKey == null) { ps.setNull(1, Types.VARCHAR); } else { ps.setString(1, userKey); }
            UserInfoBean pReturn[] = this.loadByPreparedStatement(ps);
            if (pReturn.length < 1) {
                throw new ObjectRetrievalException();
            } else {
                return pReturn[0];
            }
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Deletes rows according to its keys.
     *
     * @param userKey String - PK# 1
     * @return the number of deleted rows
     * @throws DAOException
     */
    //2
    public int deleteByPrimaryKey(String userKey) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = this.getConnection();
            StringBuffer sql = new StringBuffer("DELETE FROM user_info WHERE user_key=?");
            // System.out.println("deleteByPrimaryKey: " + sql);
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            if (userKey == null) { ps.setNull(1, Types.VARCHAR); } else { ps.setString(1, userKey); }
            return ps.executeUpdate();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    //////////////////////////////////////
    // GET/SET IMPORTED KEY BEAN METHOD
    //////////////////////////////////////
    /**
     * Retrieves the ClientBillRateBean object from the user_info.user_key field.
     *
     * @param bean the UserInfoBean
     * @return the associated ClientBillRateBean bean
     * @throws DAOException
     */
    //3.1 GET IMPORTED
    public ClientBillRateBean[] getClientBillRateBeans(UserInfoBean bean) throws DAOException
    {
        ClientBillRateBean other = ClientBillRateManager.getInstance().createClientBillRateBean();
        other.setUserKey(bean.getUserKey());
        return ClientBillRateManager.getInstance().loadUsingTemplate(other);
    }

    /**
     * Associates the UserInfoBean object to the ClientBillRateBean object.
     *
     * @param bean the UserInfoBean object to use
     * @param beanToSet the ClientBillRateBean object to associate to the UserInfoBean
     * @return the associated ClientBillRateBean bean
     */
    //4.1 SET IMPORTED
    public UserInfoBean setClientBillRateBean(UserInfoBean bean,ClientBillRateBean beanToSet)
    {
        bean.setUserKey(beanToSet.getUserKey());
        return bean;
    }




    //////////////////////////////////////
    // LOAD ALL
    //////////////////////////////////////

    /**
     * Loads all the rows from user_info.
     *
     * @return an array of UserInfoManager bean
     * @throws DAOException
     */
    //5
    public UserInfoBean[] loadAll() throws DAOException
    {
        return this.loadUsingTemplate(null);
    }


    /**
     * Loads the given number of rows from user_info, given the start row.
     *
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return an array of UserInfoManager bean
     * @throws DAOException
     */
    //6
    public UserInfoBean[] loadAll(int startRow, int numRows) throws DAOException
    {
        return this.loadUsingTemplate(null, startRow, numRows);
    }

    //////////////////////////////////////
    // SQL 'WHERE' METHOD
    //////////////////////////////////////
    /**
     * Retrieves an array of UserInfoBean given a sql 'where' clause.
     *
     * @param where the sql 'where' clause
     * @return the resulting UserInfoBean table
     * @throws DAOException
     */
    //7
    public UserInfoBean[] loadByWhere(String where) throws DAOException
    {
        return this.loadByWhere(where, null);
    }

    /**
     * Retrieves an array of UserInfoBean given a sql where clause, and a list of fields.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'WHERE' clause
     * @param fieldList array of field's ID
     * @return the resulting UserInfoBean table
     * @throws DAOException
     */
    //8
    public UserInfoBean[] loadByWhere(String where, int[] fieldList) throws DAOException
    {
        return this.loadByWhere(where, fieldList, 1, -1);
    }

    /**
     * Retrieves an array of UserInfoBean given a sql where clause and a list of fields, and startRow and numRows.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'where' clause
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return the resulting UserInfoBean table
     * @throws DAOException
     */
    //9
    public UserInfoBean[] loadByWhere(String where, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        StringBuffer sql = new StringBuffer(128);
        if(fieldList == null) {
            sql.append("SELECT ").append(ALL_FIELDS).append(" FROM user_info ").append(where);
        } else
        {
            sql.append("SELECT ");
            for(int i = 0; i < fieldList.length; i++)
            {
                if(i != 0) {
                    sql.append(",");
                }
                sql.append(FULL_FIELD_NAMES[fieldList[i]]);
            }
            sql.append(" FROM user_info ");
            sql.append(where);
        }
        Connection c = null;
        Statement st = null;
        ResultSet rs =  null;
        // System.out.println("loadByWhere: " + sql);
        try
        {
            c = this.getConnection();
            st = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = st.executeQuery(sql.toString());
            return this.decodeResultSet(rs, fieldList, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(st, rs);
            this.freeConnection(c);
        }
    }


    /**
     * Deletes all rows from user_info table.
     * @return the number of deleted rows.
     * @throws DAOException
     */
    //10
    public int deleteAll() throws DAOException
    {
        return this.deleteByWhere("");
    }


    /**
     * Deletes rows from the user_info table using a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     * <br>Attention, if 'WHERE' is omitted it will delete all records.
     *
     * @param where the sql 'where' clause
     * @return the number of deleted rows
     * @throws DAOException
     */
    //11
    public int deleteByWhere(String where) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;

        try
        {
            c = this.getConnection();
            StringBuffer sql = new StringBuffer("DELETE FROM user_info " + where);
            // System.out.println("deleteByWhere: " + sql);
            ps = c.prepareStatement(sql.toString());
            return ps.executeUpdate();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    //_____________________________________________________________________
    //
    // SAVE
    //_____________________________________________________________________
    /**
     * Saves the UserInfoBean bean into the database.
     *
     * @param bean the UserInfoBean bean to be saved
     * @return the inserted or updated bean
     * @throws DAOException
     */
    //12
    public UserInfoBean save(UserInfoBean bean) throws DAOException
    {
        if (bean.isNew()) {
            return this.insert(bean);
        } else {
            return this.update(bean);
        }
    }

    /**
     * Insert the UserInfoBean bean into the database.
     *
     * @param bean the UserInfoBean bean to be saved
     * @return the inserted bean
     * @throws DAOException
     */
    //13
    public UserInfoBean insert(UserInfoBean bean) throws DAOException
    {
        // mini checks
        if (!bean.isModified()) {
            return bean; // should not we log something ?
        }
        if (!bean.isNew()){
            return this.update(bean);
        }

        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = null;

        try
        {
            c = this.getConnection();
            this.beforeInsert(bean); // listener callback
            int _dirtyCount = 0;
            sql = new StringBuffer("INSERT into user_info (");

            if (bean.isLastUpdateModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("last_update");
                _dirtyCount++;
            }

            if (bean.isDefaultBillRateModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("default_bill_rate");
                _dirtyCount++;
            }

            if (bean.isFirstNameModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("first_name");
                _dirtyCount++;
            }

            if (bean.isLastNameModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("last_name");
                _dirtyCount++;
            }

            if (bean.isUserKeyModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("user_key");
                _dirtyCount++;
            }

            sql.append(") values (");
            if(_dirtyCount > 0) {
                sql.append("?");
                for(int i = 1; i < _dirtyCount; i++) {
                    sql.append(",?");
                }
            }
            sql.append(")");


            // System.out.println("insert : " + sql.toString());

            ps = c.prepareStatement(sql.toString(), ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

            this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            ps.executeUpdate();

            bean.isNew(false);
            bean.resetIsModified();
            this.afterInsert(bean); // listener callback
            return bean;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Update the UserInfoBean bean record in the database according to the changes.
     *
     * @param bean the UserInfoBean bean to be updated
     * @return the updated bean
     * @throws DAOException
     */
    //14
    public UserInfoBean update(UserInfoBean bean) throws DAOException
    {
        // mini checks
        if (!bean.isModified()) {
            return bean; // should not we log something ?
        }
        if (bean.isNew()){
            return this.insert(bean);
        }

        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = null;

        try
        {
            c = this.getConnection();

            this.beforeUpdate(bean); // listener callback
            sql = new StringBuffer("UPDATE user_info SET ");
            boolean useComma=false;

            if (bean.isLastUpdateModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("last_update=?");
            }

            if (bean.isDefaultBillRateModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("default_bill_rate=?");
            }

            if (bean.isFirstNameModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("first_name=?");
            }

            if (bean.isLastNameModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("last_name=?");
            }

            if (bean.isUserKeyModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("user_key=?");
            }
            sql.append(" WHERE ");
            sql.append("user_key=?");
            // System.out.println("update : " + sql.toString());
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);

            int _dirtyCount = this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            if (_dirtyCount == 0) {
                // System.out.println("The bean to look is not initialized... do not update.");
                return bean;
            }

            if (bean.getUserKey() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getUserKey()); }
            ps.executeUpdate();
            bean.resetIsModified();
            this.afterUpdate(bean); // listener callback

            return bean;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Saves an array of UserInfoBean beans into the database.
     *
     * @param beans the UserInfoBean bean table to be saved
     * @return the saved UserInfoBean array.
     * @throws DAOException
     */
    //15
    public UserInfoBean[] save(UserInfoBean[] beans) throws DAOException
    {
        for (int iIndex = 0; iIndex < beans.length; iIndex ++)
        {
            this.save(beans[iIndex]);
        }
        return beans;
    }

    /**
     * Insert an array of UserInfoBean beans into the database.
     *
     * @param beans the UserInfoBean bean table to be inserted
     * @return the saved UserInfoBean array.
     * @throws DAOException
     */
    //16
    public UserInfoBean[] insert(UserInfoBean[] beans) throws DAOException
    {
        return this.save(beans);
    }

    /**
     * Updates an array of UserInfoBean beans into the database.
     *
     * @param beans the UserInfoBean bean table to be inserted
     * @return the saved UserInfoBean array.
     * @throws DAOException
     */
    //17
    public UserInfoBean[] update(UserInfoBean[] beans) throws DAOException
    {
        return this.save(beans);
    }



    //_____________________________________________________________________
    //
    // USING TEMPLATE
    //_____________________________________________________________________
    /**
     * Loads a unique UserInfoBean bean from a template one giving a c
     *
     * @param bean the UserInfoBean bean to look for
     * @return the bean matching the template
     * @throws DAOException
     */
    //18
    public UserInfoBean loadUniqueUsingTemplate(UserInfoBean bean) throws DAOException
    {
         UserInfoBean[] beans = this.loadUsingTemplate(bean);
         if (beans.length == 0) {
             return null;
         }
         if (beans.length > 1) {
             throw new ObjectRetrievalException("More than one element !!");
         }
         return beans[0];
     }

    /**
     * Loads an array of UserInfoBean from a template one.
     *
     * @param bean the UserInfoBean template to look for
     * @return all the UserInfoBean matching the template
     * @throws DAOException
     */
    //19
    public UserInfoBean[] loadUsingTemplate(UserInfoBean bean) throws DAOException
    {
        return this.loadUsingTemplate(bean, 1, -1);
    }

    /**
     * Loads an array of UserInfoBean from a template one, given the start row and number of rows.
     *
     * @param bean the UserInfoBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return all the UserInfoBean matching the template
     * @throws DAOException
     */
    //20
    public UserInfoBean[] loadUsingTemplate(UserInfoBean bean, int startRow, int numRows) throws DAOException
    {
        return this.loadUsingTemplate(bean, startRow, numRows, SEARCH_EXACT);
    }

    /**
     * Loads an array of UserInfoBean from a template one, given the start row and number of rows.
     *
     * @param bean the UserInfoBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param searchType exact ?  like ? starting like ?
     * @return all the UserInfoBean matching the template
     * @throws DAOException
     */
    //20
    public UserInfoBean[] loadUsingTemplate(UserInfoBean bean, int startRow, int numRows, int searchType) throws DAOException
    {
        // System.out.println("loadUsingTemplate startRow:" + startRow + ", numRows:" + numRows + ", searchType:" + searchType);
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = new StringBuffer(128);
        sql.append("SELECT ").append(ALL_FIELDS).append(" FROM user_info ");
        StringBuffer sqlWhere = new StringBuffer("");

        try
        {
            if (this.fillWhere(sqlWhere, bean, searchType) > 0) {
                sql.append(" WHERE ").append(sqlWhere);
            } else {
               // System.out.println("The bean to look is not initialized... loading all");
            }
            // System.out.println("loadUsingTemplate: " + sql.toString());

            c = this.getConnection();
            int scrollType = ResultSet.TYPE_SCROLL_INSENSITIVE;
            if (startRow != 1) {
                scrollType = ResultSet.TYPE_SCROLL_SENSITIVE;
            }
            ps = c.prepareStatement(sql.toString(),
                                    scrollType,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, searchType);

            ps.executeQuery();
            return this.loadByPreparedStatement(ps, null, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }

    /**
     * Deletes rows using a UserInfoBean template.
     *
     * @param bean the UserInfoBean object(s) to be deleted
     * @return the number of deleted objects
     * @throws DAOException
     */
    //21
    public int deleteUsingTemplate(UserInfoBean bean) throws DAOException
    {
        if (bean.isUserKeyInitialized()) {
            return this.deleteByPrimaryKey(bean.getUserKey());
        }
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = new StringBuffer("DELETE FROM user_info ");
        StringBuffer sqlWhere = new StringBuffer("");

        try
        {
            this.beforeDelete(bean); // listener callback
            if (this.fillWhere(sqlWhere, bean, SEARCH_EXACT) > 0) {
                sql.append(" WHERE ").append(sqlWhere);
            } else {
               // System.out.println("The bean to look is not initialized... deleting all");
            }
            // System.out.println("deleteUsingTemplate: " + sql.toString());

            c = this.getConnection();
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            int _rows = ps.executeUpdate();
            this.afterDelete(bean); // listener callback
            return _rows;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }



    //_____________________________________________________________________
    //
    // COUNT
    //_____________________________________________________________________

    /**
     * Retrieves the number of rows of the table user_info.
     *
     * @return the number of rows returned
     * @throws DAOException
     */
    //24
    public int countAll() throws DAOException
    {
        return this.countWhere("");
    }

    /**
     * Retrieves the number of rows of the table user_info with a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the restriction clause
     * @return the number of rows returned
     * @throws DAOException
     */
    //25
    public int countWhere(String where) throws DAOException
    {
        String sql = "SELECT COUNT(*) AS MCOUNT FROM user_info " + where;
        // System.out.println("countWhere: " + sql);
        Connection c = null;
        Statement st = null;
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            c = this.getConnection();
            st = c.createStatement();
            rs =  st.executeQuery(sql);
            if (rs.next())
            {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1) {
                return iReturn;
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(st, rs);
            this.freeConnection(c);
            sql = null;
        }
        throw new DataAccessException("Error in countWhere where=[" + where + "]");
    }

    /**
     * Retrieves the number of rows of the table user_info with a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return the number of rows returned
     * @throws DAOException
     */
    //26
    private int countByPreparedStatement(PreparedStatement ps) throws DAOException
    {
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            rs = ps.executeQuery();
            if (rs.next()) {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1) {
                return iReturn;
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(rs);
        }
       throw new DataAccessException("Error in countByPreparedStatement");
    }

    /**
     * count the number of elements of a specific UserInfoBean bean
     *
     * @param bean the UserInfoBean bean to look for ant count
     * @return the number of rows returned
     * @throws DAOException
     */
    //27
    public int countUsingTemplate(UserInfoBean bean) throws DAOException
    {
        return this.countUsingTemplate(bean, -1, -1);
    }

    /**
     * count the number of elements of a specific UserInfoBean bean , given the start row and number of rows.
     *
     * @param bean the UserInfoBean template to look for and count
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return the number of rows returned
     * @throws DAOException
     */
    //20
    public int countUsingTemplate(UserInfoBean bean, int startRow, int numRows) throws DAOException
    {
        return this.countUsingTemplate(bean, startRow, numRows, SEARCH_EXACT);
    }

    /**
     * count the number of elements of a specific UserInfoBean bean given the start row and number of rows and the search type
     *
     * @param bean the UserInfoBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param searchType exact ?  like ? starting like ?
     * @return the number of rows returned
     * @throws DAOException
     */
    //20
    public int countUsingTemplate(UserInfoBean bean, int startRow, int numRows, int searchType) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = new StringBuffer("SELECT COUNT(*) AS MCOUNT FROM user_info");
        StringBuffer sqlWhere = new StringBuffer("");

        try
        {
            if (this.fillWhere(sqlWhere, bean, SEARCH_EXACT) > 0) {
                sql.append(" WHERE ").append(sqlWhere);
            } else {
                // System.out.println("The bean to look is not initialized... counting all...");
            }
            // System.out.println("countUsingTemplate: " + sql.toString());

            c = this.getConnection();
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, searchType);

            return this.countByPreparedStatement(ps);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }

    //


    /**
     * fills the given stringbuffer with the sql where clausis constructed using the bean and the search type
     * @param sqlWhere the stringbuffer that will be filled
     * @param bean the bean to use for creating the where clausis
     * @param searchType exact ?  like ? starting like ?
     * @return the number of clausis returned
     */
    protected int fillWhere(StringBuffer sqlWhere, UserInfoBean bean, int searchType)
    {
        if (bean == null) {
            return 0;
        }
        int _dirtyCount = 0;
        String sqlEqualsOperation = "=";
        if (searchType != SEARCH_EXACT) {
            sqlEqualsOperation = " like ";
        }
        try
        {
            if (bean.isLastUpdateModified()) {
                _dirtyCount ++;
                if (bean.getLastUpdate() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("last_update IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("last_update = ?");
                }
            }
            if (bean.isDefaultBillRateModified()) {
                _dirtyCount ++;
                if (bean.getDefaultBillRate() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("default_bill_rate IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("default_bill_rate = ?");
                }
            }
            if (bean.isFirstNameModified()) {
                _dirtyCount ++;
                if (bean.getFirstName() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("first_name IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("first_name ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isLastNameModified()) {
                _dirtyCount ++;
                if (bean.getLastName() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("last_name IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("last_name ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isUserKeyModified()) {
                _dirtyCount ++;
                if (bean.getUserKey() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("user_key IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("user_key ").append(sqlEqualsOperation).append("?");
                }
            }
        }
        finally
        {
            sqlEqualsOperation = null;
        }
        return _dirtyCount;
    }

    /**
     * fill the given prepared statement with the bean values and a search type
     * @param ps the preparedStatement that will be filled
     * @param bean the bean to use for creating the where clausis
     * @param searchType exact ?  like ? starting like ?
     * @return the number of clausis returned
     * @throws DAOException
     */
    protected int fillPreparedStatement(PreparedStatement ps, UserInfoBean bean, int searchType) throws DAOException
    {
        if (bean == null) {
            return 0;
        }
        int _dirtyCount = 0;
        try
        {
            if (bean.isLastUpdateModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getLastUpdate() + "]");
                if (bean.getLastUpdate() == null) { ps.setNull(++_dirtyCount, Types.TIMESTAMP); } else { ps.setTimestamp(++_dirtyCount, new java.sql.Timestamp(bean.getLastUpdate().getTime())); }
            }
            if (bean.isDefaultBillRateModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getDefaultBillRate() + "]");
                if (bean.getDefaultBillRate() == null) { ps.setNull(++_dirtyCount, Types.DOUBLE); } else { Manager.setDouble(ps, ++_dirtyCount, bean.getDefaultBillRate()); }
            }
            if (bean.isFirstNameModified()) {
                switch (searchType){
                    case SEARCH_EXACT:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getFirstName() + "]");
                        if (bean.getFirstName() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getFirstName()); }
                        break;
                    case SEARCH_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getFirstName() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getFirstName() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getFirstName() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getFirstName());
                        break;
                    case SEARCH_ENDING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getFirstName() + "]");
                        if (bean.getFirstName() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getFirstName() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isLastNameModified()) {
                switch (searchType){
                    case SEARCH_EXACT:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getLastName() + "]");
                        if (bean.getLastName() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getLastName()); }
                        break;
                    case SEARCH_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getLastName() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getLastName() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getLastName() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getLastName());
                        break;
                    case SEARCH_ENDING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getLastName() + "]");
                        if (bean.getLastName() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getLastName() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isUserKeyModified()) {
                switch (searchType){
                    case SEARCH_EXACT:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getUserKey() + "]");
                        if (bean.getUserKey() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getUserKey()); }
                        break;
                    case SEARCH_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getUserKey() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getUserKey() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getUserKey() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getUserKey());
                        break;
                    case SEARCH_ENDING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getUserKey() + "]");
                        if (bean.getUserKey() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getUserKey() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        return _dirtyCount;
    }


    //_____________________________________________________________________
    //
    // DECODE RESULT SET
    //_____________________________________________________________________

    /**
     * decode a resultset in an array of UserInfoBean objects
     *
     * @param rs the resultset to decode
     * @param fieldList table of the field's associated constants
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return the resulting UserInfoBean table
     * @throws DAOException
     */
    //28
    public UserInfoBean[] decodeResultSet(ResultSet rs, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        List v = new ArrayList();
        try
        {
            if (rs.absolute(startRow) && numRows!=0)
            {
                int count = 0;
                if(fieldList == null) {
                    do
                    {
                        v.add(decodeRow(rs));
                        count++;
                    } while ( (count<numRows||numRows<0) && rs.next() );
                }
                else {
                    do
                    {
                        v.add(decodeRow(rs, fieldList));
                        count++;
                    } while ( (count<numRows||numRows<0) && rs.next() );
                }
            }
            return (UserInfoBean[])v.toArray(new UserInfoBean[v.size()]);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            if (v != null) { v.clear(); v = null;}
        }
    }

    /**
     * Transforms a ResultSet iterating on the user_info on a UserInfoBean bean.
     *
     * @param rs the ResultSet to be transformed
     * @return bean resulting UserInfoBean bean
     * @throws DAOException
     */
    //29
    public UserInfoBean decodeRow(ResultSet rs) throws DAOException
    {
        UserInfoBean bean = this.createUserInfoBean();
        try
        {
            bean.setLastUpdate(rs.getTimestamp(1));
            bean.setDefaultBillRate(Manager.getDouble(rs, 2));
            bean.setFirstName(rs.getString(3));
            bean.setLastName(rs.getString(4));
            bean.setUserKey(rs.getString(5));
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    /**
     * Transforms a ResultSet iterating on the user_info table on a UserInfoBean bean according to a list of fields.
     *
     * @param rs the ResultSet to be transformed
     * @param fieldList table of the field's associated constants
     * @return bean resulting UserInfoBean bean
     * @throws DAOException
     */
    //30
    public UserInfoBean decodeRow(ResultSet rs, int[] fieldList) throws DAOException
    {
        UserInfoBean bean = this.createUserInfoBean();
        int pos = 0;
        try
        {
            for(int i = 0; i < fieldList.length; i++)
            {
                switch(fieldList[i])
                {
                    case ID_LAST_UPDATE:
                        ++pos;
                        bean.setLastUpdate(rs.getTimestamp(pos));
                        break;
                    case ID_DEFAULT_BILL_RATE:
                        ++pos;
                        bean.setDefaultBillRate(Manager.getDouble(rs, pos));
                        break;
                    case ID_FIRST_NAME:
                        ++pos;
                        bean.setFirstName(rs.getString(pos));
                        break;
                    case ID_LAST_NAME:
                        ++pos;
                        bean.setLastName(rs.getString(pos));
                        break;
                    case ID_USER_KEY:
                        ++pos;
                        bean.setUserKey(rs.getString(pos));
                        break;
                    default:
                        throw new DAOException("Unknown field id " + fieldList[i]);
                }
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    /**
     * Transforms a ResultSet iterating on the user_info on a UserInfoBean bean using the names of the columns
     *
     * @param rs the ResultSet to be transformed
     * @return bean resulting UserInfoBean bean
     * @throws DAOException
     */
    //31
    public UserInfoBean metaDataDecodeRow(ResultSet rs) throws DAOException
    {
        UserInfoBean bean = this.createUserInfoBean();
        try
        {
            bean.setLastUpdate(rs.getTimestamp("last_update"));
            bean.setDefaultBillRate(Manager.getDouble(rs, "default_bill_rate"));
            bean.setFirstName(rs.getString("first_name"));
            bean.setLastName(rs.getString("last_name"));
            bean.setUserKey(rs.getString("user_key"));
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }

        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    //////////////////////////////////////
    // PREPARED STATEMENT LOADER
    //////////////////////////////////////

    /**
     * Loads all the elements using a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return an array of UserInfoBean
     * @throws DAOException
     */
    //32
    public UserInfoBean[] loadByPreparedStatement(PreparedStatement ps) throws DAOException
    {
        return this.loadByPreparedStatement(ps, null);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved.
     *
     * @param ps the PreparedStatement to be used
     * @param fieldList table of the field's associated constants
     * @return an array of UserInfoBean
     * @throws DAOException
     */
    //33
    public UserInfoBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList) throws DAOException
    {
        ResultSet rs =  null;
		List v =  null;
		try
		{
		    rs =  ps.executeQuery();
		    v = new ArrayList();
			if(fieldList == null) {
				while(rs.next()) {
					v.add(decodeRow(rs));
				}
			}
			else {
				while(rs.next()) {
					v.add(decodeRow(rs, fieldList));
				}
			}

			return (UserInfoBean[])v.toArray(new UserInfoBean[0]);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            if (v != null) { v.clear(); v = null;}
            getManager().close(rs);
        }
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved,
     * and specifying the start row and the number of rows.
     *
     * @param ps the PreparedStatement to be used
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return an array of UserInfoBean
     * @throws DAOException
     */
    //34
    public UserInfoBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        ResultSet rs =  null;
        try
        {
            rs = ps.executeQuery();
            return this.decodeResultSet(rs, fieldList, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(rs);
        }
    }

    //_____________________________________________________________________
    //
    // LISTENER
    //_____________________________________________________________________
    private UserInfoListener listener = null;

    /**
     * Registers a unique UserInfoListener listener.
     */
    //35
    public void registerListener(UserInfoListener listener)
    {
        this.listener = listener;
    }

    /**
     * Before the save of the UserInfoBean bean.
     *
     * @param bean the UserInfoBean bean to be saved
     */
    //36
    private void beforeInsert(UserInfoBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeInsert(bean);
        }
    }

    /**
     * After the save of the UserInfoBean bean.
     *
     * @param bean the UserInfoBean bean to be saved
     */
    //37
    private void afterInsert(UserInfoBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterInsert(bean);
        }
    }

    /**
     * Before the update of the UserInfoBean bean.
     *
     * @param bean the UserInfoBean bean to be updated
     */
    //38
    private void beforeUpdate(UserInfoBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeUpdate(bean);
        }
    }

    /**
     * After the update of the UserInfoBean bean.
     *
     * @param bean the UserInfoBean bean to be updated
     */
    //39
    private void afterUpdate(UserInfoBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterUpdate(bean);
        }
    }

    /**
     * Before the delete of the UserInfoBean bean.
     *
     * @param bean the UserInfoBean bean to be deleted
     */
    private void beforeDelete(UserInfoBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeDelete(bean);
        }
    }

    /**
     * After the delete of the UserInfoBean bean.
     *
     * @param bean the UserInfoBean bean to be deleted
     */
    private void afterDelete(UserInfoBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterDelete(bean);
        }
    }

    //_____________________________________________________________________
    //
    // UTILS
    //_____________________________________________________________________

    /**
     * Retrieves the manager object used to get connections.
     *
     * @return the manager used
     */
    //40
    private Manager getManager()
    {
        return Manager.getInstance();
    }

    /**
     * Frees the connection.
     *
     * @param c the connection to release
     */
    //41
    private void freeConnection(Connection c)
    {
        this.getManager().releaseConnection(c); // back to pool
    }

    /**
     * Gets the connection.
     */
    //42
    private Connection getConnection() throws DAOException
    {
        try
        {
            return this.getManager().getConnection();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
    }
}
