// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package legaltime.model;

import java.util.Comparator;


/**
 * Comparator class is used to sort the VwClientHourlyRateBean objects.
 * @author sql2java
 */
public class VwClientHourlyRateComparator implements Comparator
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for VwClientHourlyRateComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new VwClientHourlyRateComparator(VwClientHourlyRateManager.ID_BILL_RATE, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>VwClientHourlyRateManager.ID_BILL_RATE
     *   <li>VwClientHourlyRateManager.ID_BILLING_PERSON
     *   <li>VwClientHourlyRateManager.ID_FIRST_NAME
     *   <li>VwClientHourlyRateManager.ID_LAST_NAME
     * </ul>
     */
    public VwClientHourlyRateComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for VwClientHourlyRateComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new VwClientHourlyRateComparator(VwClientHourlyRateManager.ID_BILL_RATE, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>VwClientHourlyRateManager.ID_BILL_RATE
     *   <li>VwClientHourlyRateManager.ID_BILLING_PERSON
     *   <li>VwClientHourlyRateManager.ID_FIRST_NAME
     *   <li>VwClientHourlyRateManager.ID_LAST_NAME
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public VwClientHourlyRateComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        VwClientHourlyRateBean b1 = (VwClientHourlyRateBean)pObj1;
        VwClientHourlyRateBean b2 = (VwClientHourlyRateBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case VwClientHourlyRateManager.ID_BILL_RATE:
                if (b1.getBillRate() == null && b2.getBillRate() != null) {
                    iReturn = -1;
                } else if (b1.getBillRate() == null && b2.getBillRate() == null) {
                    iReturn = 0;
                } else if (b1.getBillRate() != null && b2.getBillRate() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getBillRate().compareTo(b2.getBillRate());
                }
                break;
            case VwClientHourlyRateManager.ID_BILLING_PERSON:
                if (b1.getBillingPerson() == null && b2.getBillingPerson() != null) {
                    iReturn = -1;
                } else if (b1.getBillingPerson() == null && b2.getBillingPerson() == null) {
                    iReturn = 0;
                } else if (b1.getBillingPerson() != null && b2.getBillingPerson() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getBillingPerson().compareTo(b2.getBillingPerson());
                }
                break;
            case VwClientHourlyRateManager.ID_FIRST_NAME:
                if (b1.getFirstName() == null && b2.getFirstName() != null) {
                    iReturn = -1;
                } else if (b1.getFirstName() == null && b2.getFirstName() == null) {
                    iReturn = 0;
                } else if (b1.getFirstName() != null && b2.getFirstName() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getFirstName().compareTo(b2.getFirstName());
                }
                break;
            case VwClientHourlyRateManager.ID_LAST_NAME:
                if (b1.getLastName() == null && b2.getLastName() != null) {
                    iReturn = -1;
                } else if (b1.getLastName() == null && b2.getLastName() == null) {
                    iReturn = 0;
                } else if (b1.getLastName() != null && b2.getLastName() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getLastName().compareTo(b2.getLastName());
                }
                break;
            default:
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }}
