insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'AL', 'Alabama', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'AK', 'Alaska', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'AZ', 'Arizona', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'AR', 'Arkansas', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'CA', 'California', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'CO', 'Colorado', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'CT', 'Connecticut', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'DE', 'Delaware', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'FL', 'Florida', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'GA', 'Georgia', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'HI', 'Hawaii', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'ID', 'Idaho', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'IL', 'Illinois', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'IN', 'Indiana', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'IA', 'Iowa', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'KS', 'Kansas', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'KY', 'Kentucky', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'LA', 'Louisiana', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'ME', 'Maine', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'MD', 'Maryland', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'MA', 'Massachusetts', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'MI', 'Michigan', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'MN', 'Minnesota', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'MS', 'Mississippi', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'MO', 'Missouri', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'MT', 'Montana', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'NE', 'Nebraska', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'NV', 'Nevada', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'NH', 'New Hampshire', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'NJ', 'New Jersey', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'NM', 'New Mexico', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'NY', 'New York', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'NC', 'North Carolina', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'ND', 'North Dakota', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'OH', 'Ohio', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'OK', 'Oklahoma', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'OR', 'Oregon', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'PA', 'Pennsylvania', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'RI', 'Rhode Island', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'SC', 'South Carolina', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'SD', 'South Dakota', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'TN', 'Tennessee', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'TX', 'Texas', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'UT', 'Utah', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'VT', 'Vermont', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'VA', 'Virginia', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'WA', 'Washington', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'WV', 'West Virginia', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'WI', 'Wisconsin', now());
insert into sys_code( client_id, code_type, key,value,last_update)  values(1,'STATE', 'WY', 'Wyoming', now());

select * from sys_code