// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package legaltime.model;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;

import legaltime.model.Manager;
import legaltime.model.exception.DAOException;
import legaltime.model.exception.DataAccessException;
import legaltime.model.exception.ObjectRetrievalException;
import legaltime.model.PaymentLogBean;
import legaltime.model.PaymentLogManager;
import legaltime.model.ClientBean;
import legaltime.model.ClientManager;

/**
 * Handles database calls (save, load, count, etc...) for the client_account_register table.
 * @author sql2java
 */
public class ClientAccountRegisterManager 
{

    /* set =QUERY for loadUsingTemplate */
    public static final int SEARCH_EXACT = 0;
    /* set %QUERY% for loadLikeTemplate */
    public static final int SEARCH_LIKE = 1;
    /* set %QUERY for loadLikeTemplate */
    public static final int SEARCH_STARTING_LIKE = 2;
    /* set QUERY% for loadLikeTemplate */
    public static final int SEARCH_ENDING_LIKE = 3;

    /**
     * Identify the last_update field.
     */
    public static final int ID_LAST_UPDATE = 0;

    /**
     * Identify the tran_type field.
     */
    public static final int ID_TRAN_TYPE = 1;

    /**
     * Identify the tran_amt field.
     */
    public static final int ID_TRAN_AMT = 2;

    /**
     * Identify the description field.
     */
    public static final int ID_DESCRIPTION = 3;

    /**
     * Identify the effective_date field.
     */
    public static final int ID_EFFECTIVE_DATE = 4;

    /**
     * Identify the client_id field.
     */
    public static final int ID_CLIENT_ID = 5;

    /**
     * Identify the client_account_register_id field.
     */
    public static final int ID_CLIENT_ACCOUNT_REGISTER_ID = 6;

    /**
     * Contains all the full fields of the client_account_register table.
     */
    private static final String[] FULL_FIELD_NAMES =
    {
        "client_account_register.last_update"
        ,"client_account_register.tran_type"
        ,"client_account_register.tran_amt"
        ,"client_account_register.description"
        ,"client_account_register.effective_date"
        ,"client_account_register.client_id"
        ,"client_account_register.client_account_register_id"
    };

    /**
     * Contains all the fields of the client_account_register table.
     */
    public static final String[] FIELD_NAMES =
    {
        "last_update"
        ,"tran_type"
        ,"tran_amt"
        ,"description"
        ,"effective_date"
        ,"client_id"
        ,"client_account_register_id"
    };

    /**
     * Field that contains the comma separated fields of the client_account_register table.
     */
    public static final String ALL_FULL_FIELDS = "client_account_register.last_update"
                            + ",client_account_register.tran_type"
                            + ",client_account_register.tran_amt"
                            + ",client_account_register.description"
                            + ",client_account_register.effective_date"
                            + ",client_account_register.client_id"
                            + ",client_account_register.client_account_register_id";

    /**
     * Field that contains the comma separated fields of the client_account_register table.
     */
    public static final String ALL_FIELDS = "last_update"
                            + ",tran_type"
                            + ",tran_amt"
                            + ",description"
                            + ",effective_date"
                            + ",client_id"
                            + ",client_account_register_id";

    private static ClientAccountRegisterManager singleton = new ClientAccountRegisterManager();

    /**
     * Get the ClientAccountRegisterManager singleton.
     *
     * @return ClientAccountRegisterManager
     */
    public static ClientAccountRegisterManager getInstance()
    {
        return singleton;
    }


    /**
     * Creates a new ClientAccountRegisterBean instance.
     *
     * @return the new ClientAccountRegisterBean
     */
    public ClientAccountRegisterBean createClientAccountRegisterBean()
    {
        return new ClientAccountRegisterBean();
    }

    //////////////////////////////////////
    // PRIMARY KEY METHODS
    //////////////////////////////////////

    /**
     * Loads a ClientAccountRegisterBean from the client_account_register using its key fields.
     *
     * @param clientAccountRegisterId Integer - PK# 1
     * @return a unique ClientAccountRegisterBean
     * @throws DAOException
     */
    //1
    public ClientAccountRegisterBean loadByPrimaryKey(Integer clientAccountRegisterId) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = this.getConnection();
            StringBuffer sql = new StringBuffer("SELECT " + ALL_FIELDS + " FROM client_account_register WHERE client_account_register_id=?");
            // System.out.println("loadByPrimaryKey: " + sql);
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            if (clientAccountRegisterId == null) { ps.setNull(1, Types.INTEGER); } else { Manager.setInteger(ps, 1, clientAccountRegisterId); }
            ClientAccountRegisterBean pReturn[] = this.loadByPreparedStatement(ps);
            if (pReturn.length < 1) {
                throw new ObjectRetrievalException();
            } else {
                return pReturn[0];
            }
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Deletes rows according to its keys.
     *
     * @param clientAccountRegisterId Integer - PK# 1
     * @return the number of deleted rows
     * @throws DAOException
     */
    //2
    public int deleteByPrimaryKey(Integer clientAccountRegisterId) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = this.getConnection();
            StringBuffer sql = new StringBuffer("DELETE FROM client_account_register WHERE client_account_register_id=?");
            // System.out.println("deleteByPrimaryKey: " + sql);
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            if (clientAccountRegisterId == null) { ps.setNull(1, Types.INTEGER); } else { Manager.setInteger(ps, 1, clientAccountRegisterId); }
            return ps.executeUpdate();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    //////////////////////////////////////
    // GET/SET IMPORTED KEY BEAN METHOD
    //////////////////////////////////////
    /**
     * Retrieves the PaymentLogBean object from the client_account_register.client_account_register_id field.
     *
     * @param bean the ClientAccountRegisterBean
     * @return the associated PaymentLogBean bean
     * @throws DAOException
     */
    //3.1 GET IMPORTED
    public PaymentLogBean[] getPaymentLogBeans(ClientAccountRegisterBean bean) throws DAOException
    {
        PaymentLogBean other = PaymentLogManager.getInstance().createPaymentLogBean();
        other.setClientAccountRegisterId(bean.getClientAccountRegisterId());
        return PaymentLogManager.getInstance().loadUsingTemplate(other);
    }

    /**
     * Associates the ClientAccountRegisterBean object to the PaymentLogBean object.
     *
     * @param bean the ClientAccountRegisterBean object to use
     * @param beanToSet the PaymentLogBean object to associate to the ClientAccountRegisterBean
     * @return the associated PaymentLogBean bean
     */
    //4.1 SET IMPORTED
    public ClientAccountRegisterBean setPaymentLogBean(ClientAccountRegisterBean bean,PaymentLogBean beanToSet)
    {
        bean.setClientAccountRegisterId(beanToSet.getClientAccountRegisterId());
        return bean;
    }



    //////////////////////////////////////
    // GET/SET FOREIGN KEY BEAN METHOD
    //////////////////////////////////////
    /**
     * Retrieves the ClientBean object from the client_account_register.client_id field.
     *
     * @param bean the ClientAccountRegisterBean
     * @return the associated ClientBean bean
     * @throws DAOException
     */
    //3.2 GET IMPORTED VALUES
    public ClientBean getClientBean(ClientAccountRegisterBean bean) throws DAOException
    {
        ClientBean other = ClientManager.getInstance().createClientBean();
        other.setClientId(bean.getClientId()); 
        bean.setClientBean(ClientManager.getInstance().loadUniqueUsingTemplate(other)); 
        return bean.getClientBean();
    }

    /**
     * Associates the ClientAccountRegisterBean object to the ClientBean object.
     *
     * @param bean the ClientAccountRegisterBean object to use
     * @param beanToSet the ClientBean object to associate to the ClientAccountRegisterBean
     * @return the associated ClientBean bean
     * @throws Exception
     */
    //4.2 ADD IMPORTED VALUE
    public ClientBean addClientBean(ClientBean beanToSet, ClientAccountRegisterBean bean) throws Exception
    {
        beanToSet.setClientId(bean.getClientId());
        return ClientManager.getInstance().save(beanToSet);
    }

    /**
     * Associates the ClientAccountRegisterBean object to the ClientBean object.
     *
     * @param bean the ClientAccountRegisterBean object to use
     * @param beanToSet the ClientBean object to associate to the ClientAccountRegisterBean
     * @return the associated ClientBean bean
     * @throws Exception
     */
    //5.2 SET IMPORTED
    public ClientBean setClientBean(ClientAccountRegisterBean bean, ClientBean beanToSet) throws Exception
    {
        bean.setClientId(beanToSet.getClientId());
        return ClientManager.getInstance().save(beanToSet);
    }



    //////////////////////////////////////
    // LOAD ALL
    //////////////////////////////////////

    /**
     * Loads all the rows from client_account_register.
     *
     * @return an array of ClientAccountRegisterManager bean
     * @throws DAOException
     */
    //5
    public ClientAccountRegisterBean[] loadAll() throws DAOException
    {
        return this.loadUsingTemplate(null);
    }

    /**
     * Loads all the rows from client_account_register.
     *
     * @param orderBy orders the beans
     * @return an array of ClientAccountRegisterManager bean
     * @throws DAOException
     */
    //5
    public ClientAccountRegisterBean[] loadAll(String orderBy) throws DAOException
    {
        return this.loadUsingTemplate(null, orderBy);
    }




    /**
     * Loads the given number of rows from client_account_register, given the start row.
     *
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return an array of ClientAccountRegisterManager bean
     * @throws DAOException
     */
    //6
    public ClientAccountRegisterBean[] loadAll(int startRow, int numRows) throws DAOException
    {
        return this.loadUsingTemplate(null, startRow, numRows);
    }

    //////////////////////////////////////
    // SQL 'WHERE' METHOD
    //////////////////////////////////////
    /**
     * Retrieves an array of ClientAccountRegisterBean given a sql 'where' clause.
     *
     * @param where the sql 'where' clause
     * @return the resulting ClientAccountRegisterBean table
     * @throws DAOException
     */
    //7
    public ClientAccountRegisterBean[] loadByWhere(String where) throws DAOException
    {
        return this.loadByWhere(where, "", null);
    }
    public ClientAccountRegisterBean[] loadByWhere(String where, String orderBy) throws DAOException
    {
        return this.loadByWhere(where, orderBy, null);
    }

    /**
     * Retrieves an array of ClientAccountRegisterBean given a sql where clause, and a list of fields.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'WHERE' clause
     * @param fieldList array of field's ID
     * @return the resulting ClientAccountRegisterBean table
     * @throws DAOException
     */
    //8
    public ClientAccountRegisterBean[] loadByWhere(String where, String orderBy, int[] fieldList) throws DAOException
    {
        return this.loadByWhere(where, orderBy, fieldList, 1, -1);
    }

    /**
     * Retrieves an array of ClientAccountRegisterBean given a sql where clause and a list of fields, and startRow and numRows.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'where' clause
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return the resulting ClientAccountRegisterBean table
     * @throws DAOException
     */
    //9
    public ClientAccountRegisterBean[] loadByWhere(String where, String orderBy, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        StringBuffer sql = new StringBuffer(128);
        if(fieldList == null) {
            sql.append("SELECT ").append(ALL_FIELDS).append(" FROM client_account_register ").append(where);
        } else
        {
            sql.append("SELECT ");
            for(int i = 0; i < fieldList.length; i++)
            {
                if(i != 0) {
                    sql.append(",");
                }
                sql.append(FULL_FIELD_NAMES[fieldList[i]]);
            }
            sql.append(" FROM client_account_register ");
            sql.append(where);
	    sql.append(" " + orderBy);
        }
        Connection c = null;
        Statement st = null;
        ResultSet rs =  null;
        // System.out.println("loadByWhere: " + sql);
        try
        {
            c = this.getConnection();
            st = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = st.executeQuery(sql.toString());
            return this.decodeResultSet(rs, fieldList, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(st, rs);
            this.freeConnection(c);
        }
    }


    /**
     * Deletes all rows from client_account_register table.
     * @return the number of deleted rows.
     * @throws DAOException
     */
    //10
    public int deleteAll() throws DAOException
    {
        return this.deleteByWhere("");
    }


    /**
     * Deletes rows from the client_account_register table using a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     * <br>Attention, if 'WHERE' is omitted it will delete all records.
     *
     * @param where the sql 'where' clause
     * @return the number of deleted rows
     * @throws DAOException
     */
    //11
    public int deleteByWhere(String where) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;

        try
        {
            c = this.getConnection();
            StringBuffer sql = new StringBuffer("DELETE FROM client_account_register " + where);
            // System.out.println("deleteByWhere: " + sql);
            ps = c.prepareStatement(sql.toString());
            return ps.executeUpdate();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    //_____________________________________________________________________
    //
    // SAVE
    //_____________________________________________________________________
    /**
     * Saves the ClientAccountRegisterBean bean into the database.
     *
     * @param bean the ClientAccountRegisterBean bean to be saved
     * @return the inserted or updated bean
     * @throws DAOException
     */
    //12
    public ClientAccountRegisterBean save(ClientAccountRegisterBean bean) throws DAOException
    {
        if (bean.isNew()) {
            return this.insert(bean);
        } else {
            return this.update(bean);
        }
    }

    /**
     * Insert the ClientAccountRegisterBean bean into the database.
     *
     * @param bean the ClientAccountRegisterBean bean to be saved
     * @return the inserted bean
     * @throws DAOException
     */
    //13
    public ClientAccountRegisterBean insert(ClientAccountRegisterBean bean) throws DAOException
    {
        // mini checks
        if (!bean.isModified()) {
            return bean; // should not we log something ?
        }
        if (!bean.isNew()){
            return this.update(bean);
        }

        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = null;

        try
        {
            c = this.getConnection();
            this.beforeInsert(bean); // listener callback
            int _dirtyCount = 0;
            sql = new StringBuffer("INSERT into client_account_register (");

            if (bean.isLastUpdateModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("last_update");
                _dirtyCount++;
            }

            if (bean.isTranTypeModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("tran_type");
                _dirtyCount++;
            }

            if (bean.isTranAmtModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("tran_amt");
                _dirtyCount++;
            }

            if (bean.isDescriptionModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("description");
                _dirtyCount++;
            }

            if (bean.isEffectiveDateModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("effective_date");
                _dirtyCount++;
            }

            if (bean.isClientIdModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("client_id");
                _dirtyCount++;
            }

            if (bean.isClientAccountRegisterIdModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("client_account_register_id");
                _dirtyCount++;
            }

            sql.append(") values (");
            if(_dirtyCount > 0) {
                sql.append("?");
                for(int i = 1; i < _dirtyCount; i++) {
                    sql.append(",?");
                }
            }
            sql.append(")");


            // System.out.println("insert : " + sql.toString());

            ps = c.prepareStatement(sql.toString(), ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

            this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            ps.executeUpdate();

            if (!bean.isClientAccountRegisterIdModified())
            {
                PreparedStatement ps2 = null;
                ResultSet rs = null;
                try {
                    ps2 = c.prepareStatement("SELECT last_insert_id()");
                    rs = ps2.executeQuery();
                    if(rs.next()) {
                        bean.setClientAccountRegisterId(Manager.getInteger(rs, 1));
                    } else {
                        this.getManager().log("ATTENTION: Could not retrieve generated key!");
                    }
                } finally {
                    this.getManager().close(ps2, rs);
                }
            }

            bean.isNew(false);
            bean.resetIsModified();
            this.afterInsert(bean); // listener callback
            return bean;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Update the ClientAccountRegisterBean bean record in the database according to the changes.
     *
     * @param bean the ClientAccountRegisterBean bean to be updated
     * @return the updated bean
     * @throws DAOException
     */
    //14
    public ClientAccountRegisterBean update(ClientAccountRegisterBean bean) throws DAOException
    {
        // mini checks
        if (!bean.isModified()) {
            return bean; // should not we log something ?
        }
        if (bean.isNew()){
            return this.insert(bean);
        }

        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = null;

        try
        {
            c = this.getConnection();

            this.beforeUpdate(bean); // listener callback
            sql = new StringBuffer("UPDATE client_account_register SET ");
            boolean useComma=false;

            if (bean.isLastUpdateModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("last_update=?");
            }

            if (bean.isTranTypeModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("tran_type=?");
            }

            if (bean.isTranAmtModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("tran_amt=?");
            }

            if (bean.isDescriptionModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("description=?");
            }

            if (bean.isEffectiveDateModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("effective_date=?");
            }

            if (bean.isClientIdModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("client_id=?");
            }

            if (bean.isClientAccountRegisterIdModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("client_account_register_id=?");
            }
            sql.append(" WHERE ");
            sql.append("client_account_register_id=?");
            // System.out.println("update : " + sql.toString());
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);

            int _dirtyCount = this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            if (_dirtyCount == 0) {
                // System.out.println("The bean to look is not initialized... do not update.");
                return bean;
            }

            if (bean.getClientAccountRegisterId() == null) { ps.setNull(++_dirtyCount, Types.INTEGER); } else { Manager.setInteger(ps, ++_dirtyCount, bean.getClientAccountRegisterId()); }
            ps.executeUpdate();
            bean.resetIsModified();
            this.afterUpdate(bean); // listener callback

            return bean;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Saves an array of ClientAccountRegisterBean beans into the database.
     *
     * @param beans the ClientAccountRegisterBean bean table to be saved
     * @return the saved ClientAccountRegisterBean array.
     * @throws DAOException
     */
    //15
    public ClientAccountRegisterBean[] save(ClientAccountRegisterBean[] beans) throws DAOException
    {
        for (int iIndex = 0; iIndex < beans.length; iIndex ++)
        {
            this.save(beans[iIndex]);
        }
        return beans;
    }

    /**
     * Insert an array of ClientAccountRegisterBean beans into the database.
     *
     * @param beans the ClientAccountRegisterBean bean table to be inserted
     * @return the saved ClientAccountRegisterBean array.
     * @throws DAOException
     */
    //16
    public ClientAccountRegisterBean[] insert(ClientAccountRegisterBean[] beans) throws DAOException
    {
        return this.save(beans);
    }

    /**
     * Updates an array of ClientAccountRegisterBean beans into the database.
     *
     * @param beans the ClientAccountRegisterBean bean table to be inserted
     * @return the saved ClientAccountRegisterBean array.
     * @throws DAOException
     */
    //17
    public ClientAccountRegisterBean[] update(ClientAccountRegisterBean[] beans) throws DAOException
    {
        return this.save(beans);
    }



    //_____________________________________________________________________
    //
    // USING TEMPLATE
    //_____________________________________________________________________

 /**
     * Loads a unique ClientAccountRegisterBean bean from a template one giving a c
     *
     * @param bean the ClientAccountRegisterBean bean to look for
     * @return the bean matching the template
     * @throws DAOException
     */
    //18
    public ClientAccountRegisterBean loadUniqueUsingTemplate(ClientAccountRegisterBean bean) throws DAOException
    {
	return loadUniqueUsingTemplate(bean, "");

    }
    /**
     * Loads a unique ClientAccountRegisterBean bean from a template one giving a c
     *
     * @param bean the ClientAccountRegisterBean bean to look for
     * @param orderBy the order by clause for the list
     * @return the bean matching the template
     * @throws DAOException
     */
    //18
    public ClientAccountRegisterBean loadUniqueUsingTemplate(ClientAccountRegisterBean bean, String orderBy) throws DAOException
    {
         ClientAccountRegisterBean[] beans = this.loadUsingTemplate(bean,orderBy);
         if (beans.length == 0) {
             return null;
         }
         if (beans.length > 1) {
             throw new ObjectRetrievalException("More than one element !!");
         }
         return beans[0];
     }


     /**
     * Loads an array of ClientAccountRegisterBean from a template one.
     *
     * @param bean the ClientAccountRegisterBean template to look for
     * @return all the ClientAccountRegisterBean matching the template
     * @throws DAOException
     */
    //19
    public ClientAccountRegisterBean[] loadUsingTemplate(ClientAccountRegisterBean bean) throws DAOException
    {
        return this.loadUsingTemplate(bean, 1, -1, "");
    }

    /**
     * Loads an array of ClientAccountRegisterBean from a template one.
     *
     * @param bean the ClientAccountRegisterBean template to look for
     * @param orderBy the orderby clause for sql
     * @return all the ClientAccountRegisterBean matching the template
     * @throws DAOException
     */
    //19
    public ClientAccountRegisterBean[] loadUsingTemplate(ClientAccountRegisterBean bean, String orderBy) throws DAOException
    {
        return this.loadUsingTemplate(bean, 1, -1, orderBy);
    }


     /**
     * Loads an array of ClientAccountRegisterBean from a template one, given the start row and number of rows.
     *
     * @param bean the ClientAccountRegisterBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param orderBy SQL order by Clause
     * @return all the ClientAccountRegisterBean matching the template
     * @throws DAOException
     */
    //20
    public ClientAccountRegisterBean[] loadUsingTemplate(ClientAccountRegisterBean bean, int startRow, int numRows, String orderBy) throws DAOException
    {
        return this.loadUsingTemplate(bean, startRow, numRows, SEARCH_EXACT, orderBy);
    }


    /**
     * Loads an array of ClientAccountRegisterBean from a template one, given the start row and number of rows.
     *
     * @param bean the ClientAccountRegisterBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return all the ClientAccountRegisterBean matching the template
     * @throws DAOException
     */
    //20
    public ClientAccountRegisterBean[] loadUsingTemplate(ClientAccountRegisterBean bean, int startRow, int numRows) throws DAOException
    {
        return this.loadUsingTemplate(bean, startRow, numRows, SEARCH_EXACT,"");
    }

    /**
     * Loads an array of ClientAccountRegisterBean from a template one, given the start row and number of rows.
     *
     * @param bean the ClientAccountRegisterBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param searchType exact ?  like ? starting like ?
     * @param orderBy SQL orderBy Clause
     * @return all the ClientAccountRegisterBean matching the template
     * @throws DAOException
     */
    //20
    public ClientAccountRegisterBean[] loadUsingTemplate(ClientAccountRegisterBean bean, int startRow, int numRows, int searchType, String orderBy) throws DAOException
    {
        // System.out.println("loadUsingTemplate startRow:" + startRow + ", numRows:" + numRows + ", searchType:" + searchType);
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = new StringBuffer(128);
        sql.append("SELECT ").append(ALL_FIELDS).append(" FROM client_account_register ");
        StringBuffer sqlWhere = new StringBuffer("");

        try
        {
            if (this.fillWhere(sqlWhere, bean, searchType) > 0) {
                sql.append(" WHERE ").append(sqlWhere);
            } else {
               // System.out.println("The bean to look is not initialized... loading all");
            }
            // System.out.println("loadUsingTemplate: " + sql.toString());
	    sql.append(" " + orderBy);

            c = this.getConnection();
            int scrollType = ResultSet.TYPE_SCROLL_INSENSITIVE;
            if (startRow != 1) {
                scrollType = ResultSet.TYPE_SCROLL_SENSITIVE;
            }
            ps = c.prepareStatement(sql.toString(),
                                    scrollType,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, searchType);

            ps.executeQuery();
            return this.loadByPreparedStatement(ps, null, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }

    /**
     * Deletes rows using a ClientAccountRegisterBean template.
     *
     * @param bean the ClientAccountRegisterBean object(s) to be deleted
     * @return the number of deleted objects
     * @throws DAOException
     */
    //21
    public int deleteUsingTemplate(ClientAccountRegisterBean bean) throws DAOException
    {
        if (bean.isClientAccountRegisterIdInitialized()) {
            return this.deleteByPrimaryKey(bean.getClientAccountRegisterId());
        }
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = new StringBuffer("DELETE FROM client_account_register ");
        StringBuffer sqlWhere = new StringBuffer("");

        try
        {
            this.beforeDelete(bean); // listener callback
            if (this.fillWhere(sqlWhere, bean, SEARCH_EXACT) > 0) {
                sql.append(" WHERE ").append(sqlWhere);
            } else {
               // System.out.println("The bean to look is not initialized... deleting all");
            }
            // System.out.println("deleteUsingTemplate: " + sql.toString());

            c = this.getConnection();
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            int _rows = ps.executeUpdate();
            this.afterDelete(bean); // listener callback
            return _rows;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }


    //_____________________________________________________________________
    //
    // USING INDICES
    //_____________________________________________________________________

    /**
     * Retrieves an array of ClientAccountRegisterBean using the Relation_1 index.
     *
     * @param clientId the client_id column's value filter.
     * @return an array of ClientAccountRegisterBean
     * @throws DAOException
     */
    public ClientAccountRegisterBean[] loadByRelation_1(Integer clientId) throws DAOException
    {
        ClientAccountRegisterBean bean = this.createClientAccountRegisterBean();
        bean.setClientId(clientId);
        return loadUsingTemplate(bean);
    }
    
    /**
     * Deletes rows using the Relation_1 index.
     *
     * @param clientId the client_id column's value filter.
     * @return the number of deleted objects
     * @throws DAOException
     */
    public int deleteByRelation_1(Integer clientId) throws DAOException
    {
        ClientAccountRegisterBean bean = this.createClientAccountRegisterBean();
        bean.setClientId(clientId);
        return deleteUsingTemplate(bean);
    }
    


    //_____________________________________________________________________
    //
    // COUNT
    //_____________________________________________________________________

    /**
     * Retrieves the number of rows of the table client_account_register.
     *
     * @return the number of rows returned
     * @throws DAOException
     */
    //24
    public int countAll() throws DAOException
    {
        return this.countWhere("");
    }

    /**
     * Retrieves the number of rows of the table client_account_register with a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the restriction clause
     * @return the number of rows returned
     * @throws DAOException
     */
    //25
    public int countWhere(String where) throws DAOException
    {
        String sql = "SELECT COUNT(*) AS MCOUNT FROM client_account_register " + where;
        // System.out.println("countWhere: " + sql);
        Connection c = null;
        Statement st = null;
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            c = this.getConnection();
            st = c.createStatement();
            rs =  st.executeQuery(sql);
            if (rs.next())
            {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1) {
                return iReturn;
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(st, rs);
            this.freeConnection(c);
            sql = null;
        }
        throw new DataAccessException("Error in countWhere where=[" + where + "]");
    }

    /**
     * Retrieves the number of rows of the table client_account_register with a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return the number of rows returned
     * @throws DAOException
     */
    //26
    private int countByPreparedStatement(PreparedStatement ps) throws DAOException
    {
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            rs = ps.executeQuery();
            if (rs.next()) {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1) {
                return iReturn;
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(rs);
        }
       throw new DataAccessException("Error in countByPreparedStatement");
    }

    /**
     * count the number of elements of a specific ClientAccountRegisterBean bean
     *
     * @param bean the ClientAccountRegisterBean bean to look for ant count
     * @return the number of rows returned
     * @throws DAOException
     */
    //27
    public int countUsingTemplate(ClientAccountRegisterBean bean) throws DAOException
    {
        return this.countUsingTemplate(bean, -1, -1);
    }

    /**
     * count the number of elements of a specific ClientAccountRegisterBean bean , given the start row and number of rows.
     *
     * @param bean the ClientAccountRegisterBean template to look for and count
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return the number of rows returned
     * @throws DAOException
     */
    //20
    public int countUsingTemplate(ClientAccountRegisterBean bean, int startRow, int numRows) throws DAOException
    {
        return this.countUsingTemplate(bean, startRow, numRows, SEARCH_EXACT);
    }

    /**
     * count the number of elements of a specific ClientAccountRegisterBean bean given the start row and number of rows and the search type
     *
     * @param bean the ClientAccountRegisterBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param searchType exact ?  like ? starting like ?
     * @return the number of rows returned
     * @throws DAOException
     */
    //20
    public int countUsingTemplate(ClientAccountRegisterBean bean, int startRow, int numRows, int searchType) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = new StringBuffer("SELECT COUNT(*) AS MCOUNT FROM client_account_register");
        StringBuffer sqlWhere = new StringBuffer("");

        try
        {
            if (this.fillWhere(sqlWhere, bean, SEARCH_EXACT) > 0) {
                sql.append(" WHERE ").append(sqlWhere);
            } else {
                // System.out.println("The bean to look is not initialized... counting all...");
            }
            // System.out.println("countUsingTemplate: " + sql.toString());

            c = this.getConnection();
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, searchType);

            return this.countByPreparedStatement(ps);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }

    //


    /**
     * fills the given stringbuffer with the sql where clausis constructed using the bean and the search type
     * @param sqlWhere the stringbuffer that will be filled
     * @param bean the bean to use for creating the where clausis
     * @param searchType exact ?  like ? starting like ?
     * @return the number of clausis returned
     */
    protected int fillWhere(StringBuffer sqlWhere, ClientAccountRegisterBean bean, int searchType)
    {
        if (bean == null) {
            return 0;
        }
        int _dirtyCount = 0;
        String sqlEqualsOperation = "=";
        if (searchType != SEARCH_EXACT) {
            sqlEqualsOperation = " like ";
        }
        try
        {
            if (bean.isLastUpdateModified()) {
                _dirtyCount ++;
                if (bean.getLastUpdate() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("last_update IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("last_update = ?");
                }
            }
            if (bean.isTranTypeModified()) {
                _dirtyCount ++;
                if (bean.getTranType() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tran_type IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tran_type ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isTranAmtModified()) {
                _dirtyCount ++;
                if (bean.getTranAmt() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tran_amt IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tran_amt = ?");
                }
            }
            if (bean.isDescriptionModified()) {
                _dirtyCount ++;
                if (bean.getDescription() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("description IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("description ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isEffectiveDateModified()) {
                _dirtyCount ++;
                if (bean.getEffectiveDate() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("effective_date IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("effective_date = ?");
                }
            }
            if (bean.isClientIdModified()) {
                _dirtyCount ++;
                if (bean.getClientId() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("client_id IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("client_id = ?");
                }
            }
            if (bean.isClientAccountRegisterIdModified()) {
                _dirtyCount ++;
                if (bean.getClientAccountRegisterId() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("client_account_register_id IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("client_account_register_id = ?");
                }
            }
        }
        finally
        {
            sqlEqualsOperation = null;
        }
        return _dirtyCount;
    }

    /**
     * fill the given prepared statement with the bean values and a search type
     * @param ps the preparedStatement that will be filled
     * @param bean the bean to use for creating the where clausis
     * @param searchType exact ?  like ? starting like ?
     * @return the number of clausis returned
     * @throws DAOException
     */
    protected int fillPreparedStatement(PreparedStatement ps, ClientAccountRegisterBean bean, int searchType) throws DAOException
    {
        if (bean == null) {
            return 0;
        }
        int _dirtyCount = 0;
        try
        {
            if (bean.isLastUpdateModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getLastUpdate() + "]");
                if (bean.getLastUpdate() == null) { ps.setNull(++_dirtyCount, Types.TIMESTAMP); } else { ps.setTimestamp(++_dirtyCount, new java.sql.Timestamp(bean.getLastUpdate().getTime())); }
            }
            if (bean.isTranTypeModified()) {
                switch (searchType){
                    case SEARCH_EXACT:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getTranType() + "]");
                        if (bean.getTranType() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTranType()); }
                        break;
                    case SEARCH_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getTranType() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTranType() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getTranType() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTranType());
                        break;
                    case SEARCH_ENDING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getTranType() + "]");
                        if (bean.getTranType() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTranType() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isTranAmtModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getTranAmt() + "]");
                if (bean.getTranAmt() == null) { ps.setNull(++_dirtyCount, Types.DOUBLE); } else { Manager.setDouble(ps, ++_dirtyCount, bean.getTranAmt()); }
            }
            if (bean.isDescriptionModified()) {
                switch (searchType){
                    case SEARCH_EXACT:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getDescription() + "]");
                        if (bean.getDescription() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getDescription()); }
                        break;
                    case SEARCH_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getDescription() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getDescription() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getDescription() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getDescription());
                        break;
                    case SEARCH_ENDING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getDescription() + "]");
                        if (bean.getDescription() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getDescription() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isEffectiveDateModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getEffectiveDate() + "]");
                if (bean.getEffectiveDate() == null) { ps.setNull(++_dirtyCount, Types.DATE); } else { ps.setDate(++_dirtyCount, new java.sql.Date(bean.getEffectiveDate().getTime())); }
            }
            if (bean.isClientIdModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getClientId() + "]");
                if (bean.getClientId() == null) { ps.setNull(++_dirtyCount, Types.INTEGER); } else { Manager.setInteger(ps, ++_dirtyCount, bean.getClientId()); }
            }
            if (bean.isClientAccountRegisterIdModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getClientAccountRegisterId() + "]");
                if (bean.getClientAccountRegisterId() == null) { ps.setNull(++_dirtyCount, Types.INTEGER); } else { Manager.setInteger(ps, ++_dirtyCount, bean.getClientAccountRegisterId()); }
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        return _dirtyCount;
    }


    //_____________________________________________________________________
    //
    // DECODE RESULT SET
    //_____________________________________________________________________

    /**
     * decode a resultset in an array of ClientAccountRegisterBean objects
     *
     * @param rs the resultset to decode
     * @param fieldList table of the field's associated constants
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return the resulting ClientAccountRegisterBean table
     * @throws DAOException
     */
    //28
    public ClientAccountRegisterBean[] decodeResultSet(ResultSet rs, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        List v = new ArrayList();
        try
        {
            if (rs.absolute(startRow) && numRows!=0)
            {
                int count = 0;
                if(fieldList == null) {
                    do
                    {
                        v.add(decodeRow(rs));
                        count++;
                    } while ( (count<numRows||numRows<0) && rs.next() );
                }
                else {
                    do
                    {
                        v.add(decodeRow(rs, fieldList));
                        count++;
                    } while ( (count<numRows||numRows<0) && rs.next() );
                }
            }
            return (ClientAccountRegisterBean[])v.toArray(new ClientAccountRegisterBean[v.size()]);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            if (v != null) { v.clear(); v = null;}
        }
    }

    /**
     * Transforms a ResultSet iterating on the client_account_register on a ClientAccountRegisterBean bean.
     *
     * @param rs the ResultSet to be transformed
     * @return bean resulting ClientAccountRegisterBean bean
     * @throws DAOException
     */
    //29
    public ClientAccountRegisterBean decodeRow(ResultSet rs) throws DAOException
    {
        ClientAccountRegisterBean bean = this.createClientAccountRegisterBean();
        try
        {
            bean.setLastUpdate(rs.getTimestamp(1));
            bean.setTranType(rs.getString(2));
            bean.setTranAmt(Manager.getDouble(rs, 3));
            bean.setDescription(rs.getString(4));
            bean.setEffectiveDate(rs.getDate(5));
            bean.setClientId(Manager.getInteger(rs, 6));
            bean.setClientAccountRegisterId(Manager.getInteger(rs, 7));
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    /**
     * Transforms a ResultSet iterating on the client_account_register table on a ClientAccountRegisterBean bean according to a list of fields.
     *
     * @param rs the ResultSet to be transformed
     * @param fieldList table of the field's associated constants
     * @return bean resulting ClientAccountRegisterBean bean
     * @throws DAOException
     */
    //30
    public ClientAccountRegisterBean decodeRow(ResultSet rs, int[] fieldList) throws DAOException
    {
        ClientAccountRegisterBean bean = this.createClientAccountRegisterBean();
        int pos = 0;
        try
        {
            for(int i = 0; i < fieldList.length; i++)
            {
                switch(fieldList[i])
                {
                    case ID_LAST_UPDATE:
                        ++pos;
                        bean.setLastUpdate(rs.getTimestamp(pos));
                        break;
                    case ID_TRAN_TYPE:
                        ++pos;
                        bean.setTranType(rs.getString(pos));
                        break;
                    case ID_TRAN_AMT:
                        ++pos;
                        bean.setTranAmt(Manager.getDouble(rs, pos));
                        break;
                    case ID_DESCRIPTION:
                        ++pos;
                        bean.setDescription(rs.getString(pos));
                        break;
                    case ID_EFFECTIVE_DATE:
                        ++pos;
                        bean.setEffectiveDate(rs.getDate(pos));
                        break;
                    case ID_CLIENT_ID:
                        ++pos;
                        bean.setClientId(Manager.getInteger(rs, pos));
                        break;
                    case ID_CLIENT_ACCOUNT_REGISTER_ID:
                        ++pos;
                        bean.setClientAccountRegisterId(Manager.getInteger(rs, pos));
                        break;
                    default:
                        throw new DAOException("Unknown field id " + fieldList[i]);
                }
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    /**
     * Transforms a ResultSet iterating on the client_account_register on a ClientAccountRegisterBean bean using the names of the columns
     *
     * @param rs the ResultSet to be transformed
     * @return bean resulting ClientAccountRegisterBean bean
     * @throws DAOException
     */
    //31
    public ClientAccountRegisterBean metaDataDecodeRow(ResultSet rs) throws DAOException
    {
        ClientAccountRegisterBean bean = this.createClientAccountRegisterBean();
        try
        {
            bean.setLastUpdate(rs.getTimestamp("last_update"));
            bean.setTranType(rs.getString("tran_type"));
            bean.setTranAmt(Manager.getDouble(rs, "tran_amt"));
            bean.setDescription(rs.getString("description"));
            bean.setEffectiveDate(rs.getDate("effective_date"));
            bean.setClientId(Manager.getInteger(rs, "client_id"));
            bean.setClientAccountRegisterId(Manager.getInteger(rs, "client_account_register_id"));
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }

        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    //////////////////////////////////////
    // PREPARED STATEMENT LOADER
    //////////////////////////////////////

    /**
     * Loads all the elements using a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return an array of ClientAccountRegisterBean
     * @throws DAOException
     */
    //32
    public ClientAccountRegisterBean[] loadByPreparedStatement(PreparedStatement ps) throws DAOException
    {
        return this.loadByPreparedStatement(ps, null);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved.
     *
     * @param ps the PreparedStatement to be used
     * @param fieldList table of the field's associated constants
     * @return an array of ClientAccountRegisterBean
     * @throws DAOException
     */
    //33
    public ClientAccountRegisterBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList) throws DAOException
    {
        ResultSet rs =  null;
		List v =  null;
		try
		{
		    rs =  ps.executeQuery();
		    v = new ArrayList();
			if(fieldList == null) {
				while(rs.next()) {
					v.add(decodeRow(rs));
				}
			}
			else {
				while(rs.next()) {
					v.add(decodeRow(rs, fieldList));
				}
			}

			return (ClientAccountRegisterBean[])v.toArray(new ClientAccountRegisterBean[0]);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            if (v != null) { v.clear(); v = null;}
            getManager().close(rs);
        }
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved,
     * and specifying the start row and the number of rows.
     *
     * @param ps the PreparedStatement to be used
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return an array of ClientAccountRegisterBean
     * @throws DAOException
     */
    //34
    public ClientAccountRegisterBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        ResultSet rs =  null;
        try
        {
            rs = ps.executeQuery();
            return this.decodeResultSet(rs, fieldList, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(rs);
        }
    }

    //_____________________________________________________________________
    //
    // LISTENER
    //_____________________________________________________________________
    private ClientAccountRegisterListener listener = null;

    /**
     * Registers a unique ClientAccountRegisterListener listener.
     */
    //35
    public void registerListener(ClientAccountRegisterListener listener)
    {
        this.listener = listener;
    }

    /**
     * Before the save of the ClientAccountRegisterBean bean.
     *
     * @param bean the ClientAccountRegisterBean bean to be saved
     */
    //36
    private void beforeInsert(ClientAccountRegisterBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeInsert(bean);
        }
    }

    /**
     * After the save of the ClientAccountRegisterBean bean.
     *
     * @param bean the ClientAccountRegisterBean bean to be saved
     */
    //37
    private void afterInsert(ClientAccountRegisterBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterInsert(bean);
        }
    }

    /**
     * Before the update of the ClientAccountRegisterBean bean.
     *
     * @param bean the ClientAccountRegisterBean bean to be updated
     */
    //38
    private void beforeUpdate(ClientAccountRegisterBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeUpdate(bean);
        }
    }

    /**
     * After the update of the ClientAccountRegisterBean bean.
     *
     * @param bean the ClientAccountRegisterBean bean to be updated
     */
    //39
    private void afterUpdate(ClientAccountRegisterBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterUpdate(bean);
        }
    }

    /**
     * Before the delete of the ClientAccountRegisterBean bean.
     *
     * @param bean the ClientAccountRegisterBean bean to be deleted
     */
    private void beforeDelete(ClientAccountRegisterBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeDelete(bean);
        }
    }

    /**
     * After the delete of the ClientAccountRegisterBean bean.
     *
     * @param bean the ClientAccountRegisterBean bean to be deleted
     */
    private void afterDelete(ClientAccountRegisterBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterDelete(bean);
        }
    }

    //_____________________________________________________________________
    //
    // UTILS
    //_____________________________________________________________________

    /**
     * Retrieves the manager object used to get connections.
     *
     * @return the manager used
     */
    //40
    private Manager getManager()
    {
        return Manager.getInstance();
    }

    /**
     * Frees the connection.
     *
     * @param c the connection to release
     */
    //41
    private void freeConnection(Connection c)
    {
        this.getManager().releaseConnection(c); // back to pool
    }

    /**
     * Gets the connection.
     */
    //42
    private Connection getConnection() throws DAOException
    {
        try
        {
            return this.getManager().getConnection();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
    }
}
