// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package legaltime.model;

import java.util.Comparator;


/**
 * Comparator class is used to sort the ExpenseInvoiceItemBean objects.
 * @author sql2java
 */
public class ExpenseInvoiceItemComparator implements Comparator
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for ExpenseInvoiceItemComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new ExpenseInvoiceItemComparator(ExpenseInvoiceItemManager.ID_LAST_UPDATE, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>ExpenseInvoiceItemManager.ID_LAST_UPDATE
     *   <li>ExpenseInvoiceItemManager.ID_INVOICE_ID
     *   <li>ExpenseInvoiceItemManager.ID_HOURS_BILLED
     *   <li>ExpenseInvoiceItemManager.ID_EXPENSE_DESCRIPTION
     *   <li>ExpenseInvoiceItemManager.ID_EXPENSE_DATE
     *   <li>ExpenseInvoiceItemManager.ID_EXPENSE_INVOICE_ITEM_ID
     * </ul>
     */
    public ExpenseInvoiceItemComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for ExpenseInvoiceItemComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new ExpenseInvoiceItemComparator(ExpenseInvoiceItemManager.ID_LAST_UPDATE, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>ExpenseInvoiceItemManager.ID_LAST_UPDATE
     *   <li>ExpenseInvoiceItemManager.ID_INVOICE_ID
     *   <li>ExpenseInvoiceItemManager.ID_HOURS_BILLED
     *   <li>ExpenseInvoiceItemManager.ID_EXPENSE_DESCRIPTION
     *   <li>ExpenseInvoiceItemManager.ID_EXPENSE_DATE
     *   <li>ExpenseInvoiceItemManager.ID_EXPENSE_INVOICE_ITEM_ID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public ExpenseInvoiceItemComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        ExpenseInvoiceItemBean b1 = (ExpenseInvoiceItemBean)pObj1;
        ExpenseInvoiceItemBean b2 = (ExpenseInvoiceItemBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case ExpenseInvoiceItemManager.ID_LAST_UPDATE:
                if (b1.getLastUpdate() == null && b2.getLastUpdate() != null) {
                    iReturn = -1;
                } else if (b1.getLastUpdate() == null && b2.getLastUpdate() == null) {
                    iReturn = 0;
                } else if (b1.getLastUpdate() != null && b2.getLastUpdate() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getLastUpdate().compareTo(b2.getLastUpdate());
                }
                break;
            case ExpenseInvoiceItemManager.ID_INVOICE_ID:
                if (b1.getInvoiceId() == null && b2.getInvoiceId() != null) {
                    iReturn = -1;
                } else if (b1.getInvoiceId() == null && b2.getInvoiceId() == null) {
                    iReturn = 0;
                } else if (b1.getInvoiceId() != null && b2.getInvoiceId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getInvoiceId().compareTo(b2.getInvoiceId());
                }
                break;
            case ExpenseInvoiceItemManager.ID_HOURS_BILLED:
                if (b1.getHoursBilled() == null && b2.getHoursBilled() != null) {
                    iReturn = -1;
                } else if (b1.getHoursBilled() == null && b2.getHoursBilled() == null) {
                    iReturn = 0;
                } else if (b1.getHoursBilled() != null && b2.getHoursBilled() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getHoursBilled().compareTo(b2.getHoursBilled());
                }
                break;
            case ExpenseInvoiceItemManager.ID_EXPENSE_DESCRIPTION:
                if (b1.getExpenseDescription() == null && b2.getExpenseDescription() != null) {
                    iReturn = -1;
                } else if (b1.getExpenseDescription() == null && b2.getExpenseDescription() == null) {
                    iReturn = 0;
                } else if (b1.getExpenseDescription() != null && b2.getExpenseDescription() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getExpenseDescription().compareTo(b2.getExpenseDescription());
                }
                break;
            case ExpenseInvoiceItemManager.ID_EXPENSE_DATE:
                if (b1.getExpenseDate() == null && b2.getExpenseDate() != null) {
                    iReturn = -1;
                } else if (b1.getExpenseDate() == null && b2.getExpenseDate() == null) {
                    iReturn = 0;
                } else if (b1.getExpenseDate() != null && b2.getExpenseDate() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getExpenseDate().compareTo(b2.getExpenseDate());
                }
                break;
            case ExpenseInvoiceItemManager.ID_EXPENSE_INVOICE_ITEM_ID:
                if (b1.getExpenseInvoiceItemId() == null && b2.getExpenseInvoiceItemId() != null) {
                    iReturn = -1;
                } else if (b1.getExpenseInvoiceItemId() == null && b2.getExpenseInvoiceItemId() == null) {
                    iReturn = 0;
                } else if (b1.getExpenseInvoiceItemId() != null && b2.getExpenseInvoiceItemId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getExpenseInvoiceItemId().compareTo(b2.getExpenseInvoiceItemId());
                }
                break;
            default:
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }}
