--delete from ledger_account;

insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),1,'Root Account','ROOT',1,'' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),100,'Assets','ASSET',1,'Assets' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),101,'Investments','ASSET',1,'Investments' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),102,'Brokerage Account','BANK',1,'Brokerage Account' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),103,'Bond','STOCK',1,'Bond' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),104,'Stock','STOCK',1,'Stock' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),105,'Market Index','MUTUAL',1,'Market Index' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),106,'Mutual Fund','MUTUAL',1,'Mutual Fund' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),107,'Current Assets','ASSET',1,'Current Assets' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),108,'Checking Account','BANK',1,'Checking Account' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),109,'Savings Account','BANK',1,'Savings Account' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),110,'Cash in Wallet','CASH',1,'Cash in Wallet' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),111,'Bank CD','BANK',1,'Bank CD' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),112,'Money Market','BANK',1,'Money Market' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),113,'Petty Cash','CASH',1,'Petty Cash' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),114,'Accounts Receivable','RECEIVABLE',1,'Accounts Receivable' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),201,'Income','INCOME',1,'Income' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),202,'Dividend Income','INCOME',1,'Dividend Income' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),203,'Interest Income','INCOME',1,'Interest Income' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),204,'Bond Interest','INCOME',1,'Bond Interest' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),205,'Checking Interest','INCOME',1,'Checking Interest' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),206,'Other Interest','INCOME',1,'Other Interest' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),207,'Savings Interest','INCOME',1,'Savings Interest' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),208,'CD Interest','INCOME',1,'CD Interest' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),209,'Money Market Interest','INCOME',1,'Money Market Interest' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),210,'Other Income','INCOME',1,'Other Income' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),211,'Salary','INCOME',1,'Salary' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),212,'Sales','INCOME',1,'Sales' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),301,'Expenses','EXPENSE',1,'Expenses' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),302,'Commissions','EXPENSE',1,'Commissions' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),303,'Adjustment','EXPENSE',1,'Adjustment' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),304,'Auto','EXPENSE',1,'Auto' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),305,'Fees','EXPENSE',1,'Fees' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),306,'Gas','EXPENSE',1,'Gas' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),307,'Parking','EXPENSE',1,'Parking' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),308,'Repair and Maintenance','EXPENSE',1,'Repair and Maintenance' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),309,'Bank Service Charge','EXPENSE',1,'Bank Service Charge' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),310,'Books','EXPENSE',1,'Books' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),311,'Cable','EXPENSE',1,'Cable' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),312,'Charity','EXPENSE',1,'Charity' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),313,'Computer','EXPENSE',1,'Computer' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),314,'Dining','EXPENSE',1,'Dining' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),315,'Education','EXPENSE',1,'Education' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),316,'Entertainment','EXPENSE',1,'Entertainment' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),317,'Recreation','EXPENSE',1,'Recreation' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),318,'Travel','EXPENSE',1,'Travel' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),319,'Gifts','EXPENSE',1,'Gifts' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),320,'Insurance','EXPENSE',1,'Insurance' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),321,'Auto Insurance','EXPENSE',1,'Auto Insurance' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),322,'Health Insurance','EXPENSE',1,'Health Insurance' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),323,'Life Insurance','EXPENSE',1,'Life Insurance' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),324,'Disability Insurance','EXPENSE',1,'Disability Insurance' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),325,'Liability Insurance','EXPENSE',1,'Liability Insurance' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),326,'Workers Comp','EXPENSE',1,'Workers Comp' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),327,'Medical Expenses','EXPENSE',1,'Medical Expenses' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),328,'Miscellaneous','EXPENSE',1,'Miscellaneous' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),329,'Online Services','EXPENSE',1,'Online Services' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),330,'Phone','EXPENSE',1,'Phone' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),331,'Public Transportation','EXPENSE',1,'Public Transportation' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),332,'Subscriptions','EXPENSE',1,'Subscriptions' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),333,'Supplies','EXPENSE',1,'Supplies' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),334,'Taxes','EXPENSE',1,'Taxes' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),335,'Federal','EXPENSE',1,'Federal' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),336,'Medicare','EXPENSE',1,'Medicare' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),337,'Other Tax','EXPENSE',1,'Other Tax' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),338,'Social Security','EXPENSE',1,'Social Security' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),339,'State/Province','EXPENSE',1,'State/Province' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),340,'Emp-FICA','EXPENSE',1,'Employer SS/Med' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),341,'FICA','EXPENSE',1,'SS/Med' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),342,'FUTA','EXPENSE',1,'FUTA' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),343,'Local','EXPENSE',1,'Local' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),344,'Property','EXPENSE',1,'Property' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),345,'Utilities','EXPENSE',1,'Utilities' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),346,'Electric','EXPENSE',1,'Electric' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),347,'Garbage collection','EXPENSE',1,'Garbage collection' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),348,'Gas','EXPENSE',1,'Gas' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),349,'Water','EXPENSE',1,'Water' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),350,'Cable','EXPENSE',1,'Cable' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),351,'Cell Phone','EXPENSE',1,'Cell Phone' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),352,'Internet','EXPENSE',1,'Internet' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),353,'Phone','EXPENSE',1,'Phone' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),354,'Cash Discounts','EXPENSE',1,'Cash Discounts' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),355,'Depreciation','EXPENSE',1,'Depreciation' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),356,'Dues and Subscriptions','EXPENSE',1,'Dues and Subscriptions' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),357,'Equipment Rental','EXPENSE',1,'Equipment Rental' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),358,'Licenses and Permits','EXPENSE',1,'Licenses and Permits' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),359,'Office Supplies','EXPENSE',1,'Office Supplies' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),360,'Outside Services','EXPENSE',1,'Outside Services' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),361,'Payroll Expenses','EXPENSE',1,'Payroll Expenses' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),362,'Postage and Delivery','EXPENSE',1,'Postage and Delivery' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),363,'Printing and Reproduction','EXPENSE',1,'Printing and Reproduction' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),364,'Professional Fees','EXPENSE',1,'Professional Fees' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),365,'Accounting','EXPENSE',1,'Accounting' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),366,'Legal Fees','EXPENSE',1,'Legal Fees' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),367,'Rent','EXPENSE',1,'Rent' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),368,'Repairs','EXPENSE',1,'Repairs' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),369,'Building Repairs','EXPENSE',1,'Building Repairs' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),370,'Computer Repairs','EXPENSE',1,'Computer Repairs' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),371,'Equipment Repairs','EXPENSE',1,'Equipment Repairs' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),372,'Janitorial Expenses','EXPENSE',1,'Janitorial Expenses' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),373,'Travel and Entertainment','EXPENSE',1,'Travel and Entertainment' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),374,'Entertainment','EXPENSE',1,'Entertainment' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),375,'Meals','EXPENSE',1,'Meals' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),376,'Travel','EXPENSE',1,'Travel' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),400,'Liabilities','LIABILITY',1,'Liabilities' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),401,'Accounts Payable','PAYABLE',1,'Accounts Payable' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),500,'Equity','EQUITY',1,'Equity' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),501,'Opening Balances','EQUITY',1,'Opening Balances' );
insert into ledger_account(client_id,last_update,ledger_account_id,name, account_type, ledger_commodity_id,description) values(1,now(),502,'Retained Earnings','EQUITY',1,'Retained Earnings' );

update ledger_account set parent_account_id = 100 where ledger_account_id >100 and ledger_account_id<200;
update ledger_account set parent_account_id = 200 where ledger_account_id >200 and ledger_account_id<300;
update ledger_account set parent_account_id = 300 where ledger_account_id >300 and ledger_account_id<400;
update ledger_account set parent_account_id = 400 where ledger_account_id >400 and ledger_account_id<500;
update ledger_account set parent_account_id = 500 where ledger_account_id >500 and ledger_account_id<600;
update ledger_account set parent_account_id = 1 where ledger_account_id =100;
update ledger_account set parent_account_id = 1 where ledger_account_id =200;
update ledger_account set parent_account_id = 1 where ledger_account_id =300;
update ledger_account set parent_account_id = 1 where ledger_account_id =400;
update ledger_account set parent_account_id = 1 where ledger_account_id =500;